## Data Mapping the Metabolomics

In [34]:
import sys, os
sys.path.insert(0, "/Users/trivenidhamdhere/Documents/MSc Data Science/MSc Dissertation - AZ/src/scripts")

import re
import pandas as pd
from data_utils import load_clean_parquets, preview

pd.set_option('display.max_columns', 20)
pd.set_option('display.width', 120)

In [35]:
tables = load_clean_parquets()
hpa_rna = tables["hpa_rna"]
depmap_expr = tables["depmap_expr"]
geo_expr = tables["geo_expr"]
proteomics = tables["proteomics"]
protein_map = tables["protein_map"]
fusions = tables["fusions"]
mutations = tables["mutations"]
cellosaurus = tables["cellosaurus"]
depmap_profiles = tables["depmap_profiles"]
sample_info = tables["sample_info"]
geo_info = tables["geo_info"]
hpa_desc = tables["hpa_desc"]
metabolomics = tables["metabolomics"]
mirna = tables["mirna"]
signatures = tables["signatures"]

Loaded hpa_rna: (24315372, 6)
Loaded depmap_expr: (1495, 53961)
Loaded geo_expr: (19914, 3268)
Loaded proteomics: (375, 12559)
Loaded protein_map: (12558, 3)
Loaded fusions: (184237, 32)
Loaded mutations: (1066869, 70)
Loaded cellosaurus: (152231, 17)
Loaded depmap_profiles: (3830, 5)
Loaded sample_info: (1840, 29)
Loaded geo_info: (3267, 23)
Loaded hpa_desc: (1206, 7)
Loaded metabolomics: (928, 227)
Loaded mirna: (734, 956)
Loaded signatures: (3021, 12)

In [36]:
import numpy as np
import pandas as pd

def audit(df: pd.DataFrame) -> pd.DataFrame:
    n = len(df)
    miss = df.isna().sum()
    pct = (miss.to_numpy(dtype=float) / n * 100).round(1) if n else np.zeros(len(miss))
    return (pd.DataFrame({
        "column":    miss.index,
        "dtype":     df.dtypes.astype(str).to_numpy(),
        "missing_n": miss.to_numpy(),
        "missing_%": pct,
    })
    .sort_values("missing_%", ascending=False)
    .reset_index(drop=True))

## Metabolomics

In [37]:
metabolomics

,ccle_id,depmap_id,2-aminoadipate,3-phosphoglycerate,alpha-glycerophosphate,4-pyridoxate,aconitate,adenine,adipate,alpha-ketoglutarate,...,c56:8 tag,c56:7 tag,c56:6 tag,c56:5 tag,c56:4 tag,c56:3 tag,c56:2 tag,c58:8 tag,c58:7 tag,c58:6 tag
0,dms53_lung,ach-000698,6.112727,6.034198,5.896896,6.000532,5.513618,5.868529,5.977177,5.693074,...,6.070239,6.133433,6.091089,6.257711,6.372732,6.202511,5.939576,6.309821,6.115974,5.999436
1,sw1116_large_intestine,ach-000489,5.577413,5.727045,5.111468,6.073250,5.802494,5.824473,5.888821,5.768379,...,6.248653,6.633575,6.378052,6.341043,6.360945,6.333540,6.137271,7.065858,6.832174,6.363064
2,ncih1694_lung,ach-000431,5.886398,5.574881,5.541259,5.848375,5.665026,5.875548,5.894904,5.839640,...,5.942887,5.946988,5.837980,5.913350,6.137530,5.807546,5.704149,5.881193,5.785208,5.504225
3,p3hr1_haematopoietic_and_lymphoid_tissue,ach-000707,5.770030,6.099229,6.233259,5.543495,5.767759,6.155905,6.111148,5.949481,...,6.516922,6.113791,6.282113,6.248667,6.109480,6.043570,5.846802,6.429402,5.779815,6.241530
4,hut78_haematopoietic_and_lymphoid_tissue,ach-000509,5.480683,5.469742,6.509397,6.251005,5.190578,5.897085,6.148333,5.607481,...,6.161981,6.777932,6.676390,6.695659,6.751029,6.385056,6.682612,6.757899,6.728570,6.879260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,sf268_central_nervous_system,ach-000655,5.977636,6.026483,6.480536,6.112056,5.878324,5.732508,5.981183,6.459139,...,5.547818,5.703861,5.581725,5.506887,5.362247,5.322091,5.556126,5.544802,4.897559,5.506999
924,sf539_central_nervous_system,ach-000273,5.957233,6.090834,5.323475,6.145795,5.741201,5.605435,6.184192,6.004195,...,5.713210,5.651439,5.720680,5.387960,5.275798,5.289684,5.494241,5.533795,5.139488,5.452544
925,snb75_central_nervous_system,ach-000504,5.967707,5.931487,5.620542,5.955261,5.935244,5.384674,5.955886,6.239657,...,5.605403,5.317500,5.630315,5.433324,5.330957,5.481404,5.570553,5.146598,5.010639,5.114385
926,hop92_lung,ach-000825,5.962415,5.992640,6.296222,5.916386,6.043984,5.883976,5.954731,6.181054,...,5.949798,6.249271,6.248746,6.130000,5.873297,5.826041,5.997694,6.411166,6.105394,6.387275
927,mutz3_haematopoietic_and_lymphoid_tissue,ach-000084,6.332344,5.812531,5.446330,6.469052,5.501232,6.469954,6.136017,5.479015,...,6.588558,6.548211,6.667652,6.868391,6.598519,5.956474,6.022471,6.862916,7.045115,6.841075

In [38]:
audit(metabolomics)

                       column    dtype  missing_n  missing_%
0                   depmap_id      str          1        0.1
1                   c18:1 lpc  float64          0        0.0
2                   c20:4 lpc  float64          0        0.0
3                   c20:3 lpc  float64          0        0.0
4                   c22:6 lpc  float64          0        0.0
..                        ...      ...        ...        ...
222  cis/trans-hydroxyproline  float64          0        0.0
223                 ornithine  float64          0        0.0
224                citrulline  float64          0        0.0
225                   taurine  float64          0        0.0
226                 c58:6 tag  float64          0        0.0

[227 rows x 4 columns]

**Key Findings**
1. There is one missing n in deepmap id
2. Decision - check with other files - look for ccle name/id and get the missing depmapid

In [39]:
sample_info

,depmap_id,cell_line_name,stripped_cell_line_name,ccle_name,alias,cosmicid,sex,source,rrid,wtsi_master_cell_id,...,lineage_sub_subtype,lineage_molecular_subtype,default_growth_pattern,model_manipulation,model_manipulation_details,patient_id,parent_depmap_id,cellosaurus_ncit_disease,cellosaurus_ncit_id,cellosaurus_issues
0,ach-000016,slr 21,slr21,slr21_kidney,NaN,NaN,NaN,academic lab,cvcl_v607,NaN,...,NaN,NaN,NaN,NaN,NaN,pt-jnarlb,NaN,clear cell renal cell carcinoma,c4033,NaN
1,ach-000032,mhh-call-3,mhhcall3,mhhcall3_haematopoietic_and_lymphoid_tissue,NaN,NaN,female,dsmz,cvcl_0089,NaN,...,b_cell,NaN,NaN,NaN,NaN,pt-p2koyi,NaN,childhood b acute lymphoblastic leukemia,c9140,NaN
2,ach-000033,nci-h1819,ncih1819,ncih1819_lung,NaN,NaN,female,academic lab,cvcl_1497,NaN,...,nsclc_adenocarcinoma,NaN,NaN,NaN,NaN,pt-9p1wqv,NaN,lung adenocarcinoma,c3512,NaN
3,ach-000043,hs 895.t,hs895t,hs895t_fibroblast,NaN,NaN,female,atcc,cvcl_0993,NaN,...,NaN,NaN,2d: adherent,NaN,NaN,pt-rtuvzq,NaN,melanoma,c3224,NaN
4,ach-000049,hek te,hekte,hekte_kidney,NaN,NaN,NaN,academic lab,cvcl_ws59,NaN,...,NaN,NaN,NaN,immortalized,NaN,pt-qwyygr,NaN,NaN,NaN,no information is available about this cell li...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1835,ach-002393,cro-ap3,croap3,croap3_haematopoietic_and_lymphoid_tissue,NaN,NaN,male,sanger,cvcl_1810,NaN,...,b_cell_primary_effusion,NaN,NaN,NaN,NaN,pt-tc0lzm,NaN,primary effusion lymphoma,c6915,NaN
1836,ach-002394,geo,geo,geo_large_intestine,NaN,NaN,NaN,sanger,cvcl_0271,NaN,...,NaN,NaN,NaN,NaN,NaN,pt-fa1q9q,NaN,colon carcinoma,c4910,NaN
1837,ach-002395,huh-6 clone 5,huh6clone5,huh6clone5_liver,NaN,NaN,male,sanger,cvcl_1296,NaN,...,NaN,NaN,NaN,NaN,NaN,pt-ttixsl,ach-000671,hepatoblastoma,c3728,NaN
1838,ach-002396,sarc9371,sarc9371,sarc9371_bone,NaN,NaN,NaN,sanger,cvcl_5g89,NaN,...,NaN,NaN,NaN,NaN,NaN,pt-715fdc,NaN,osteosarcoma,c9145,NaN
1839,ach-002397,kmh-2,kmhdash2,kmh2_thyroid,NaN,2054094.0,male,NaN,cvcl_s641,NaN,...,NaN,NaN,NaN,NaN,NaN,pt-ix8rhj,NaN,thyroid gland anaplastic carcinoma,c3878,NaN

In [40]:
import pandas as pd

# --- 1. Isolate the missing-id row ---
miss = metabolomics[metabolomics["depmap_id"].isna()]
print(f"missing rows: {len(miss)}  |  index: {miss.index.tolist()}")

missing rows: 1  |  index: [553]

In [41]:
# --- Map oc315_ovary -> depmap_id via sample_info ---
id_col = next(c for c in sample_info.columns if c in ("depmap_id"))
sname  = next(c for c in sample_info.columns if "ccle" in c and "name" in c)

key = metabolomics.loc[553, "ccle_id"].strip().upper()   # 'OC315_OVARY'
hit = sample_info.loc[sample_info[sname].str.strip().str.upper() == key, id_col]
print(hit)

138    ach-001144
Name: depmap_id, dtype: str

In [42]:
before = metabolomics["depmap_id"].notna().sum()
metabolomics.loc[553, "depmap_id"] = hit.iloc[0]
after = metabolomics["depmap_id"].notna().sum()
assert after == before + 1
print(f"filled row 553 -> {hit.iloc[0]}  ({before} -> {after})")

filled row 553 -> ach-001144  (927 -> 928)

In [43]:
# --- Build the two name->id maps ---
id_col = next(c for c in sample_info.columns if c in ("depmap_id","modelid","model_id"))
sname  = next(c for c in sample_info.columns if "ccle" in c and "name" in c)

meta_pairs = (metabolomics[["ccle_id", "depmap_id"]]
              .assign(ccle_key=lambda d: d["ccle_id"].str.strip().str.upper()))

si_pairs = (sample_info[[sname, id_col]]
            .rename(columns={sname: "ccle_id_si", id_col: "depmap_id_si"})
            .assign(ccle_key=lambda d: d["ccle_id_si"].str.strip().str.upper()))

# --- Merge on the ccle name and compare the two depmap_ids ---
chk = meta_pairs.merge(si_pairs, on="ccle_key", how="left")

# how many metabolomics names even resolve in sample_info?
unmatched = chk["depmap_id_si"].isna().sum()
print(f"names not found in sample_info: {unmatched} / {len(chk)}")

# where metabolomics already had an id, does it agree with sample_info?
both = chk[chk["depmap_id"].notna() & chk["depmap_id_si"].notna()]
mismatch = both[both["depmap_id"] != both["depmap_id_si"]]
print(f"rows with both ids: {len(both)}  |  disagreements: {len(mismatch)}")
if len(mismatch):
    print(mismatch[["ccle_id", "depmap_id", "depmap_id_si"]].to_string())

# --- The row we care about: 553 (oc315_ovary) ---
print("\nrow 553 resolution:")
print(chk.loc[553, ["ccle_id", "depmap_id", "depmap_id_si"]])

names not found in sample_info: 3 / 928
rows with both ids: 925  |  disagreements: 0

row 553 resolution:
ccle_id         oc315_ovary
depmap_id        ach-001144
depmap_id_si     ach-001144
Name: 553, dtype: str

In [44]:
audit(metabolomics)

                       column    dtype  missing_n  missing_%
0                     ccle_id      str          0        0.0
1                    c16:1 sm  float64          0        0.0
2                   c20:4 lpc  float64          0        0.0
3                   c20:3 lpc  float64          0        0.0
4                   c22:6 lpc  float64          0        0.0
..                        ...      ...        ...        ...
222  cis/trans-hydroxyproline  float64          0        0.0
223                 ornithine  float64          0        0.0
224                citrulline  float64          0        0.0
225                   taurine  float64          0        0.0
226                 c58:6 tag  float64          0        0.0

[227 rows x 4 columns]

In [45]:
# metabolomics and protemics: depmap_id is an ACH- id, so -> model_id is clean
metabolomics = metabolomics.rename(columns={"depmap_id": "model_id"})

proteomics = proteomics.rename(columns={"depmap_id": "model_id"})

In [46]:
from pathlib import Path

out = Path("/Users/trivenidhamdhere/Documents/MSc Data Science/"
           "MSc Dissertation - AZ/cleaned_track_data")
out.mkdir(parents=True, exist_ok=True)

# final sanity check before writing
assert metabolomics["model_id"].isna().sum() == 0, "metabolomics still has missing ids"

for name, df in [("metabolomics", metabolomics)]:
    path = out / f"{name}.parquet"
    df.to_parquet(path, engine="fastparquet", index=False)
    print(f"saved {name}: {df.shape[0]} rows x {df.shape[1]} cols -> {path}")

saved metabolomics: 928 rows x 227 cols -> /Users/trivenidhamdhere/Documents/MSc Data Science/MSc Dissertation - AZ/cleaned_track_data/metabolomics.parquet