In [21]:
import sys, os
_notebook_dir = os.path.dirname(os.path.abspath('__file__'))
sys.path.insert(0, os.path.join(_notebook_dir, '..', 'scripts'))

from pathlib import Path
import pandas as pd
import numpy as np
from src.scripts.data_utils import load_raw_parquets, load_clean_parquets, REF

PROJECT_ROOT = os.path.abspath(os.path.join(REF, '..'))
print('notebook dir:', _notebook_dir)
print('project root:', PROJECT_ROOT)

notebook dir: D:\MSc Data Science\Dissertation\AstraZeneca\UoB-GeneTraceAI-25-26
project root: D:\MSc Data Science\Dissertation\AstraZeneca\UoB-GeneTraceAI-25-26

In [83]:
tables = load_raw_parquets()

Loaded hpa_rna: (24315372, 6)
Loaded depmap_expr: (1495, 53961)
Loaded geo_expr: (19914, 3268)
Loaded proteomics: (375, 12559)
Loaded fusions: (184237, 30)
Loaded mutations: (1066869, 70)
Loaded cellosaurus: (152231, 17)
Loaded depmap_profiles: (3830, 5)
Loaded sample_info: (1840, 29)
Loaded geo_info: (3267, 23)
Loaded hpa_desc: (1206, 7)
Loaded metabolomics: (928, 227)
Loaded mirna: (734, 956)
Loaded signatures: (3021, 12)

In [84]:
tables_cleaned = load_clean_parquets()

Loaded hpa_rna: (24315372, 6)
Loaded depmap_expr: (1495, 53961)
Loaded geo_expr: (19914, 3268)
Loaded proteomics: (375, 12559)
Loaded protein_map: (12558, 3)
Loaded fusions: (184237, 32)
Loaded mutations: (1066869, 70)
Loaded cellosaurus: (152231, 17)
Loaded depmap_profiles: (3830, 5)
Loaded sample_info: (1840, 29)
Loaded geo_info: (3267, 23)
Loaded hpa_desc: (1206, 7)
Loaded metabolomics: (928, 227)
Loaded mirna: (734, 956)
Loaded signatures: (3021, 12)

In [85]:
df_cellosaurus = tables["cellosaurus"]
df_cellosaurus_clean = tables_cleaned["cellosaurus"]

df_cellosaurus_clean.head()

,cellosaurus_cell_line_name,cellosaurus_accession,secondary accession number(s),synonyms,cross-references,references identifiers,web pages,comments,str profile data,diseases,species of origin,hierarchy,originate from same individual,sex of cell,age of donor at sampling,category,date (entry history)
0,#132 pc3-1-sc-e8,cvcl_b0t9,NaN,z48-5mg-70,wikidata; q108819335,patent=ep0501779a1;,NaN,group: patented cell line. || registration: in...,NaN,NaN,ncbi_taxid=10090; ! mus musculus (mouse),cvcl_d145 ! hl-1 friendly myeloma-653,NaN,NaN,NaN,hybridoma,created: 23-09-21; last updated: 30-01-24; ver...
1,#132 pl12 sc-d1,cvcl_b0t8,NaN,z48-5mg-63,wikidata; q108819336,patent=ep0501779a1;,NaN,group: patented cell line. || registration: in...,NaN,NaN,ncbi_taxid=10090; ! mus musculus (mouse),cvcl_d145 ! hl-1 friendly myeloma-653,NaN,NaN,NaN,hybridoma,created: 23-09-21; last updated: 30-01-24; ver...
2,#15310-ln,cvcl_e548,NaN,15310-ln; ter461; ter-461; ter 461; ter479; te...,dbmhc; 48439 || ecacc; 94050311 || ihw; ihw093...,NaN,http://pathology.ucla.edu/workfiles/360cx.pdf ...,part of: 12th international histocompatibility...,NaN,NaN,ncbi_taxid=9606; ! homo sapiens (human),NaN,NaN,female,age unspecified,transformed cell line,created: 22-10-12; last updated: 30-01-24; ver...
3,#16-15,cvcl_ka96,NaN,NaN,rcb; rcb4635 || wikidata; q54422067,pubmed=25400923;,NaN,monoclonal antibody isotype: igm. || monoclona...,NaN,NaN,ncbi_taxid=10090; ! mus musculus (mouse) || nc...,cvcl_4032 ! p3x63ag8.653,NaN,NaN,NaN,hybridoma,created: 22-08-17; last updated: 21-03-23; ver...
4,#40a,cvcl_iw91,NaN,NaN,wikidata; q54422071,pubmed=28159921;,NaN,characteristics: established from parent cell ...,NaN,ncit; c21619; mouse mesothelioma,ncbi_taxid=10090; ! mus musculus (mouse),cvcl_iw90 ! 40,NaN,male,1-2m,cancer cell line,created: 15-05-17; last updated: 29-06-23; ver...

In [86]:
df_cellosaurus.columns

Index(['Identifier (cell line name)', 'Accession (CVCL_xxxx)',
       'Secondary accession number(s)', 'Synonyms', 'Cross-references',
       'References identifiers', 'Web pages', 'Comments', 'STR profile data',
       'Diseases', 'Species of origin', 'Hierarchy',
       'Originate from same individual', 'Sex of cell',
       'Age of donor at sampling', 'Category', 'Date (entry history)'],
      dtype='str')

In [87]:
df_sample_info = tables["sample_info"]
df_sample_info_cleaned = tables_cleaned["sample_info"]

df_sample_info_cleaned.head()

,depmap_id,cell_line_name,stripped_cell_line_name,ccle_name,alias,cosmicid,sex,source,rrid,wtsi_master_cell_id,...,lineage_sub_subtype,lineage_molecular_subtype,default_growth_pattern,model_manipulation,model_manipulation_details,patient_id,parent_depmap_id,cellosaurus_ncit_disease,cellosaurus_ncit_id,cellosaurus_issues
0,ach-000016,slr 21,slr21,slr21_kidney,NaN,NaN,NaN,academic lab,cvcl_v607,NaN,...,NaN,NaN,NaN,NaN,NaN,pt-jnarlb,NaN,clear cell renal cell carcinoma,c4033,NaN
1,ach-000032,mhh-call-3,mhhcall3,mhhcall3_haematopoietic_and_lymphoid_tissue,NaN,NaN,female,dsmz,cvcl_0089,NaN,...,b_cell,NaN,NaN,NaN,NaN,pt-p2koyi,NaN,childhood b acute lymphoblastic leukemia,c9140,NaN
2,ach-000033,nci-h1819,ncih1819,ncih1819_lung,NaN,NaN,female,academic lab,cvcl_1497,NaN,...,nsclc_adenocarcinoma,NaN,NaN,NaN,NaN,pt-9p1wqv,NaN,lung adenocarcinoma,c3512,NaN
3,ach-000043,hs 895.t,hs895t,hs895t_fibroblast,NaN,NaN,female,atcc,cvcl_0993,NaN,...,NaN,NaN,2d: adherent,NaN,NaN,pt-rtuvzq,NaN,melanoma,c3224,NaN
4,ach-000049,hek te,hekte,hekte_kidney,NaN,NaN,NaN,academic lab,cvcl_ws59,NaN,...,NaN,NaN,NaN,immortalized,NaN,pt-qwyygr,NaN,NaN,NaN,no information is available about this cell li...

In [88]:
df_sample_info_cleaned.columns

Index(['depmap_id', 'cell_line_name', 'stripped_cell_line_name', 'ccle_name',
       'alias', 'cosmicid', 'sex', 'source', 'rrid', 'wtsi_master_cell_id',
       'sample_collection_site', 'primary_or_metastasis', 'primary_disease',
       'subtype', 'age', 'sanger_model_id', 'depmap_public_comments',
       'lineage', 'lineage_subtype', 'lineage_sub_subtype',
       'lineage_molecular_subtype', 'default_growth_pattern',
       'model_manipulation', 'model_manipulation_details', 'patient_id',
       'parent_depmap_id', 'cellosaurus_ncit_disease', 'cellosaurus_ncit_id',
       'cellosaurus_issues'],
      dtype='str')

In [89]:
df_sample_info_cleaned.shape

(1840, 29)

In [90]:
df_depmap_profiles = tables["depmap_profiles"]
df_depmap_profiles_cleaned = tables_cleaned["depmap_profiles"]


df_depmap_profiles_cleaned.head()

   profileid  modelcondition     modelid datatype weskit
0  pr-00utu3  mc-001131-kkjv  ach-001131      wgs    NaN
1  pr-01r7om  mc-000957-yckn  ach-000957      rna    NaN
2  pr-02xmlg  mc-002785-qo9e  ach-002785      rna    NaN
3  pr-04vvbz  mc-001289-bpdi  ach-001289      wes    ice
4  pr-09gmei  mc-000520-yim7  ach-000520      rna    NaN

In [91]:
df_depmap_profiles_cleaned.shape

(3830, 5)

In [92]:
df_depmap_profiles_cleaned.modelid.nunique()

1822

## HARMONIZATION

In [93]:
rrid_valid = df_sample_info['RRID'].str.match(r'^CVCL_', na=False)
print(f"RRID populated: {df_sample_info['RRID'].notna().sum()} / {len(df_sample_info)}")
print(f"RRID well-formed CVCL: {rrid_valid.sum()}")

RRID populated: 1818 / 1840
RRID well-formed CVCL: 1818

In [94]:
direct_match = df_sample_info['RRID'].isin(
        df_cellosaurus['Accession (CVCL_xxxx)']
    )
print(f"Direct RRID -> Accession match: {direct_match.sum()} / {len(df_sample_info)}")

Direct RRID -> Accession match: 1816 / 1840

In [95]:
needs_fallback = df_sample_info[~direct_match]
print(f"Rows needing name fallback: {len(needs_fallback)}")

Rows needing name fallback: 24

### sample_info

In [96]:
# Null value check
assert df_sample_info['DepMap_ID'].isna().sum() == 0

In [97]:
# Duplicated key check
assert df_sample_info['DepMap_ID'].duplicated().sum() == 0

### cellosaurus

In [98]:
# Null value check
assert df_cellosaurus['Accession (CVCL_xxxx)'].duplicated().sum() == 0

In [99]:
# Duplicated key check
assert df_cellosaurus['Accession (CVCL_xxxx)'].isna().sum() == 0

### depmap_profiles

In [100]:
# Informational only - ModelID duplicate count.
# ModelID is NOT a unique key in this table and no combination of
# (ModelID, Datatype, WESKit) is either (models can have multiple WES
# profiles from different capture kits, and even that combination repeats,
# likely from re-sequencing batches). ProfileID (checked below) is the only
# column in this table that is actually guaranteed unique - do not assert
# uniqueness on ModelID or any partial combination of these columns.
df_depmap_profiles[["ModelID", "Datatype", "WESKit"]].duplicated().sum()

np.int64(123)

In [101]:
# Informational only - ModelID-alone duplicate count (expected > 0, see cell above)
df_depmap_profiles["ModelID"].duplicated().sum()

np.int64(2008)

In [102]:
# Duplicated key check - ProfileID
assert df_depmap_profiles["ProfileID"].duplicated().sum() == 0

In [103]:
# Null value check - ModelID
assert df_depmap_profiles["ModelID"].isna().sum() == 0

#### ASSERTING CLEANED COLUMNS

#### sample_info cleaned

In [104]:
df_sample_info_cleaned.columns

Index(['depmap_id', 'cell_line_name', 'stripped_cell_line_name', 'ccle_name',
       'alias', 'cosmicid', 'sex', 'source', 'rrid', 'wtsi_master_cell_id',
       'sample_collection_site', 'primary_or_metastasis', 'primary_disease',
       'subtype', 'age', 'sanger_model_id', 'depmap_public_comments',
       'lineage', 'lineage_subtype', 'lineage_sub_subtype',
       'lineage_molecular_subtype', 'default_growth_pattern',
       'model_manipulation', 'model_manipulation_details', 'patient_id',
       'parent_depmap_id', 'cellosaurus_ncit_disease', 'cellosaurus_ncit_id',
       'cellosaurus_issues'],
      dtype='str')

In [105]:
# Null value check
assert df_sample_info_cleaned['depmap_id'].isna().sum() == 0

In [106]:
# Duplicated key check
assert df_sample_info_cleaned['depmap_id'].duplicated().sum() == 0

#### cellosuarus cleaned

In [107]:
df_cellosaurus_clean.columns

Index(['cellosaurus_cell_line_name', 'cellosaurus_accession',
       'secondary accession number(s)', 'synonyms', 'cross-references',
       'references identifiers', 'web pages', 'comments', 'str profile data',
       'diseases', 'species of origin', 'hierarchy',
       'originate from same individual', 'sex of cell',
       'age of donor at sampling', 'category', 'date (entry history)'],
      dtype='str')

In [108]:
# Null value check
assert df_cellosaurus_clean['cellosaurus_accession'].duplicated().sum() == 0

In [109]:
# Duplicated key check
assert df_cellosaurus_clean['cellosaurus_accession'].isna().sum() == 0

#### depmap_profile cleaned

In [110]:
df_depmap_profiles_cleaned.columns

Index(['profileid', 'modelcondition', 'modelid', 'datatype', 'weskit'], dtype='str')

In [111]:
# Informational only - modelid duplicate count on the pre-pivot table.
# same issue as the depmap_profiles QA block above - modelid is not
# unique here because a model can have multiple profile rows (rna/wgs/wes,
# multiple WES kits, resequencing batches). This table gets pivoted to one
# row per model later (df_depmap_profiles_cleaned_pivoted); do not assert
# modelid uniqueness before that pivot happens.
df_depmap_profiles_cleaned["modelid"].duplicated().sum()

np.int64(2008)

In [112]:
# print the sum of the Duplicated value check - ModelID
print(df_depmap_profiles_cleaned["modelid"].duplicated().sum())

2008

In [113]:
df_depmap_profiles_cleaned.shape

(3830, 5)

In [114]:
# Null key check - ModelID
assert df_depmap_profiles_cleaned["modelid"].isna().sum() == 0

In [115]:
# Null key check - ModelID
assert df_depmap_profiles_cleaned["profileid"].duplicated().sum() == 0

In [116]:
df_depmap_profiles_cleaned.loc[
    df_depmap_profiles_cleaned["modelid"].duplicated(keep=False),
]

      profileid  modelcondition     modelid datatype   weskit
1     pr-01r7om  mc-000957-yckn  ach-000957      rna      NaN
2     pr-02xmlg  mc-002785-qo9e  ach-002785      rna      NaN
3     pr-04vvbz  mc-001289-bpdi  ach-001289      wes      ice
4     pr-09gmei  mc-000520-yim7  ach-000520      rna      NaN
7     pr-0c2lny  mc-000074-qybw  ach-000074      wes  agilent
...         ...             ...         ...      ...      ...
3825  pr-zym15a  mc-000796-mvbn  ach-000796      wes  agilent
3826  pr-zytjvt  mc-000278-uc8l  ach-000278      wgs      NaN
3827  pr-zzhtvc  mc-000231-teoc  ach-000231      rna      NaN
3828  pr-zzjqoa  mc-000310-adwh  ach-000310      wes      ice
3829  pr-zzpc09  mc-001172-cktb  ach-001172      rna      NaN

[3429 rows x 5 columns]

In [117]:
# Check the datatype combinations exist per modelid 
df_depmap_profiles_cleaned.groupby("modelid")["datatype"].apply(lambda x: sorted(x.unique())).value_counts()

datatype
[rna, wes]         954
[rna, wes, wgs]    365
[wes]              323
[rna, wgs]          88
[rna]               72
[wes, wgs]          12
[wgs]                8
Name: count, dtype: int64

In [118]:
# Boolean coverage flags (your existing pivot)
flags_pivoted = (
    df_depmap_profiles_cleaned
    .assign(flag=True)
    .pivot_table(
        index="modelid",
        columns="datatype",
        values="flag",
        aggfunc="any",
        fill_value=False
    )
    .reset_index()
    .rename(columns=lambda c: f"has_{c}" if c != "modelid" else c)
)

flags_pivoted.head()

datatype     modelid  has_rna  has_wes  has_wgs
0         ach-000001     True     True     True
1         ach-000002     True     True    False
2         ach-000003     True    False    False
3         ach-000004     True     True    False
4         ach-000005     True     True     True

In [119]:
# Pivot modelcondition per datatype (one column per datatype)
modelcondition_pivoted = (
    df_depmap_profiles_cleaned
    .pivot_table(
        index="modelid",
        columns="datatype",
        values="modelcondition",
        aggfunc="first"   
    )
    .reset_index()
    .rename(columns=lambda c: f"modelcondition_{c}" if c != "modelid" else c)
)

modelcondition_pivoted.head()

datatype     modelid modelcondition_rna modelcondition_wes modelcondition_wgs
0         ach-000001     mc-000001-ztia     mc-000001-zu8p     mc-000001-ztia
1         ach-000002     mc-000002-8qny     mc-000002-updl                NaN
2         ach-000003     mc-000003-dwgn                NaN                NaN
3         ach-000004     mc-000004-pa3k     mc-000004-pa3k                NaN
4         ach-000005     mc-000005-aycs     mc-000005-aycs     mc-000005-aycs

In [120]:
# Pivot weskit per datatype (only meaningful for 'wes', will be NaN elsewhere)
weskit_pivoted = (
    df_depmap_profiles_cleaned
    .pivot_table(
        index="modelid",
        columns="datatype",
        values="weskit",
        aggfunc="first"
    )
    .reset_index()
    .rename(columns=lambda c: f"weskit_{c}" if c != "modelid" else c)
)

weskit_pivoted.head()

datatype     modelid weskit_wes
0         ach-000001    agilent
1         ach-000002    agilent
2         ach-000004        ice
3         ach-000005        ice
4         ach-000006    agilent

In [121]:
df_depmap_profiles_cleaned_pivoted = (
    flags_pivoted
    .merge(modelcondition_pivoted, on="modelid", how="left")
    .merge(weskit_pivoted, on="modelid", how="left")
)

assert df_depmap_profiles_cleaned_pivoted["modelid"].duplicated().sum() == 0
print(f"Shape: {df_depmap_profiles_cleaned_pivoted.shape}")

df_depmap_profiles_cleaned_pivoted.head()

Shape: (1822, 8)

datatype,modelid,has_rna,has_wes,has_wgs,modelcondition_rna,modelcondition_wes,modelcondition_wgs,weskit_wes
0,ach-000001,True,True,True,mc-000001-ztia,mc-000001-zu8p,mc-000001-ztia,agilent
1,ach-000002,True,True,False,mc-000002-8qny,mc-000002-updl,NaN,agilent
2,ach-000003,True,False,False,mc-000003-dwgn,NaN,NaN,NaN
3,ach-000004,True,True,False,mc-000004-pa3k,mc-000004-pa3k,NaN,ice
4,ach-000005,True,True,True,mc-000005-aycs,mc-000005-aycs,mc-000005-aycs,ice

In [122]:
print(f"modelid+datatype duplicate pairs: {df_depmap_profiles_cleaned.duplicated(subset=["modelid", "datatype"]).sum()}")

modelid+datatype duplicate pairs: 224

In [123]:
df_depmap_profiles_cleaned.loc[
    df_depmap_profiles_cleaned.duplicated(subset=["modelid", "datatype"])
]

      profileid  modelcondition     modelid datatype   weskit
248   pr-3x4ri2  mc-001453-lwrm  ach-001453      wes      ice
504   pr-81ikhg  mc-000745-kwjq  ach-000745      wes  agilent
521   pr-8br5s3  mc-000329-gbth  ach-000329      wes  agilent
583   pr-97jle2  mc-001360-kfdj  ach-001360      wes      ice
594   pr-9bhyji  mc-000095-ucyl  ach-000095      rna      NaN
...         ...             ...         ...      ...      ...
3797  pr-zr0jbj  mc-000055-ndma  ach-000055      wes  agilent
3812  pr-zv0mdh  mc-001321-4zqp  ach-001321      wes  agilent
3813  pr-zvd6kc  mc-000337-vmhg  ach-000337      rna      NaN
3818  pr-zwqrih  mc-002029-jzk3  ach-002029      wes      ice
3822  pr-zxbcmo  mc-000662-1qhs  ach-000662      wes  agilent

[224 rows x 5 columns]

### Key to aggregate the tables:
- depmap_profile: modelid
- cellosaurus: cellosaurus_accession
- sample_info: depmap_id, rrid

In [124]:
df_cellosaurus_clean["cellosaurus_accession"]

0         cvcl_b0t9
1         cvcl_b0t8
2         cvcl_e548
3         cvcl_ka96
4         cvcl_iw91
            ...
152226    cvcl_zb29
152227    cvcl_zb30
152228    cvcl_a3zf
152229    cvcl_c6u7
152230    cvcl_3449
Name: cellosaurus_accession, Length: 152231, dtype: str

In [125]:
df_sample_info_cleaned["rrid"]

0       cvcl_v607
1       cvcl_0089
2       cvcl_1497
3       cvcl_0993
4       cvcl_ws59
          ...
1835    cvcl_1810
1836    cvcl_0271
1837    cvcl_1296
1838    cvcl_5g89
1839    cvcl_s641
Name: rrid, Length: 1840, dtype: str

In [126]:
rrid_valid_id = set(df_sample_info_cleaned["rrid"]) 

print("Mapped cellosaurus_accession & rrid map ratio:", df_cellosaurus_clean[df_cellosaurus_clean["cellosaurus_accession"].isin(rrid_valid_id)]["cellosaurus_accession"].count())
print("Mis-Mapped cellosaurus_accession & rrid map ratio:", df_cellosaurus_clean[~df_cellosaurus_clean["cellosaurus_accession"].isin(rrid_valid_id)]["cellosaurus_accession"].count())

Mapped cellosaurus_accession & rrid map ratio: 1812
Mis-Mapped cellosaurus_accession & rrid map ratio: 150419

In [127]:
# --- STEP 1: Normalize both keys ---
cvcl_norm = df_cellosaurus_clean["cellosaurus_accession"].str.strip().str.upper()
rrid_norm  = df_sample_info_cleaned["rrid"].str.strip().str.upper()

cvcl_set = set(cvcl_norm)
rrid_set  = set(rrid_norm)

print("=== After normalization ===")
print("Matched :", len(cvcl_set & rrid_set))
print("rrid NOT in cellosaurus:", len(rrid_set - cvcl_set))

# --- STEP 2: Inspect the 28 unmatched rrid values ---
unmatched = rrid_set - cvcl_set
print("\nUnmatched rrid sample:", list(unmatched)[:15])

# --- STEP 3: Prefix audit ---
print("\nrrid prefix distribution:")
print(df_sample_info_cleaned["rrid"].str[:5].value_counts().head(10))

print("\ncellosaurus_accession prefix distribution:")
print(df_cellosaurus_clean["cellosaurus_accession"].str[:5].value_counts().head(10))

# --- STEP 4: Length distribution (detects padding/extra chars) ---
print("\nrrid length stats:")
print(df_sample_info_cleaned["rrid"].str.len().describe())

print("\ncellosaurus_accession length stats:")
print(df_cellosaurus_clean["cellosaurus_accession"].str.len().describe())

# --- STEP 5: Check for 'RRID:' prefix in rrid column ---
has_rrid_prefix = df_sample_info_cleaned["rrid"].str.startswith("RRID:").sum()
print(f"\nEntries with 'RRID:' prefix in sample_info: {has_rrid_prefix}")

=== After normalization ===
Matched : 1812
rrid NOT in cellosaurus: 3

Unmatched rrid sample: ['CVCL_X507', 'CVCL_V618', nan]

rrid prefix distribution:
rrid
cvcl_    1818
Name: count, dtype: int64

cellosaurus_accession prefix distribution:
cellosaurus_accession
cvcl_    152231
Name: count, dtype: int64

rrid length stats:
count    1818.0
mean        9.0
std         0.0
min         9.0
25%         9.0
50%         9.0
75%         9.0
max         9.0
Name: rrid, dtype: float64

cellosaurus_accession length stats:
count    152231.0
mean          9.0
std           0.0
min           9.0
25%           9.0
50%           9.0
75%           9.0
max           9.0
Name: cellosaurus_accession, dtype: float64

Entries with 'RRID:' prefix in sample_info: 0

In [128]:
df_sample_info_cleaned["depmap_id"]

0       ach-000016
1       ach-000032
2       ach-000033
3       ach-000043
4       ach-000049
           ...
1835    ach-002393
1836    ach-002394
1837    ach-002395
1838    ach-002396
1839    ach-002397
Name: depmap_id, Length: 1840, dtype: str

In [129]:
df_depmap_profiles_cleaned_pivoted["modelid"]

0       ach-000001
1       ach-000002
2       ach-000003
3       ach-000004
4       ach-000005
           ...
1817    ach-003157
1818    ach-003158
1819    ach-003159
1820    ach-003160
1821    ach-003161
Name: modelid, Length: 1822, dtype: str

In [130]:
depmap_id_valid = set(df_sample_info_cleaned["depmap_id"]) 

print("Mapped depmap_id & modelid map ratio:", df_depmap_profiles_cleaned_pivoted[df_depmap_profiles_cleaned_pivoted["modelid"].isin(depmap_id_valid)]["modelid"].count())
print("Mis-Mapped depmap_id & modelid map ratio:", df_depmap_profiles_cleaned_pivoted[~df_depmap_profiles_cleaned_pivoted["modelid"].isin(depmap_id_valid)]["modelid"].count())

Mapped depmap_id & modelid map ratio: 1749
Mis-Mapped depmap_id & modelid map ratio: 73

In [131]:
depmap_set  = set(df_sample_info_cleaned["depmap_id"].dropna().str.strip().str.lower())
modelid_set = set(df_depmap_profiles_cleaned_pivoted["modelid"].dropna().str.strip().str.lower())

# Both directions
in_sample_not_profile = depmap_set - modelid_set
in_profile_not_sample = modelid_set - depmap_set

print("sample_info NaN depmap_id     :", df_sample_info_cleaned["depmap_id"].isna().sum())
print("depmap_profiles NaN modelid   :", df_depmap_profiles_cleaned_pivoted["modelid"].isna().sum())
print("depmap_id NOT in modelid      :", len(in_sample_not_profile))
print("modelid NOT in depmap_id      :", len(in_profile_not_sample))

# Format audit
print("\nSample depmap_id prefix   :", df_sample_info_cleaned["depmap_id"].str[:4].value_counts())
print("Sample modelid prefix      :", df_depmap_profiles_cleaned_pivoted["modelid"].str[:4].value_counts())
print("\nSample depmap_id length   :", df_sample_info_cleaned["depmap_id"].str.len().describe())
print("Sample modelid length      :", df_depmap_profiles_cleaned_pivoted["modelid"].str.len().describe())

# Inspect mismatches
print("\nSample unmatched depmap_id :", list(in_sample_not_profile)[:10])
print("Sample unmatched modelid   :", list(in_profile_not_sample)[:10])

sample_info NaN depmap_id     : 0
depmap_profiles NaN modelid   : 0
depmap_id NOT in modelid      : 91
modelid NOT in depmap_id      : 73

Sample depmap_id prefix   : depmap_id
ach-    1840
Name: count, dtype: int64
Sample modelid prefix      : modelid
ach-    1822
Name: count, dtype: int64

Sample depmap_id length   : count    1840.0
mean       10.0
std         0.0
min        10.0
25%        10.0
50%        10.0
75%        10.0
max        10.0
Name: depmap_id, dtype: float64
Sample modelid length      : count    1822.0
mean       10.0
std         0.0
min        10.0
25%        10.0
50%        10.0
75%        10.0
max        10.0
Name: modelid, dtype: float64

Sample unmatched depmap_id : ['ach-001007', 'ach-002378', 'ach-001357', 'ach-002394', 'ach-001000', 'ach-002874', 'ach-002172', 'ach-001187', 'ach-001072', 'ach-001042']
Sample unmatched modelid   : ['ach-002784', 'ach-001847', 'ach-003143', 'ach-003154', 'ach-002799', 'ach-003136', 'ach-002781', 'ach-002478', 'ach-001481', 'ach-002522']

### OVERALL DATA LOSS ACROSS THE THREE DATASET 
1. **Three datasets in scope** → `cellosaurus_clean` (152,231 rows), `sample_info_cleaned` (1,840 rows), `depmap_profiles_pivoted` (1,822 rows) all keyed on uniform, fixed-length identifiers (`cvcl_` / `ach-`).

2. **Cellosaurus ↔ sample_info** (via `cellosaurus_accession` ↔ `rrid`) → **24 records lost** 22 due to null `rrid` at source, 2 due to secondary/deprecated accessions absent from the provided dump.

3. **sample_info ↔ depmap_profiles** (via `depmap_id` ↔ `modelid`) → **91 records lost** from sample_info side, **73 records lost** from depmap_profiles side caused purely by DepMap release version mismatch between datasets.

4. **Zero format-related losses** across all three joins no case mismatches, no prefix pollution, no null keys in DepMap join, no length inconsistencies detected.

5. **Cumulative loss from sample_info anchor** → `24 (Cellosaurus) + 91 (DepMap) = 115 records` affected across both integrations (overlap unknown without three-way join).

6. **Final harmonized coverage** → Cellosaurus join retains **98.48%** (1,812/1,840); DepMap join retains **95.05%** (1,749/1,840); three-way intersection is the effective working dataset.

7. **Total irrecoverable loss** → **115 records maximum (6.25% of sample_info)** split between source nulls, snapshot version gaps, and deprecated registry entries; none resolvable within the provided data environment.

> **Note:** the numbers above are the *initial pre-recovery* estimate. See "REDUCE THE DATA LOSS" below for the multi-tier recovery cascade, and "INSIGHTS FROM THE HARMONIZATION" for the actual final coverage after fixes.

### REDUCE THE DATA LOSS

In [132]:
# Check if sample_info has name columns
print("Sample_info :", df_sample_info_cleaned.columns.tolist())
print("\n---------\n")
print("cellosaurus :",df_cellosaurus_clean.columns.tolist())

Sample_info : ['depmap_id', 'cell_line_name', 'stripped_cell_line_name', 'ccle_name', 'alias', 'cosmicid', 'sex', 'source', 'rrid', 'wtsi_master_cell_id', 'sample_collection_site', 'primary_or_metastasis', 'primary_disease', 'subtype', 'age', 'sanger_model_id', 'depmap_public_comments', 'lineage', 'lineage_subtype', 'lineage_sub_subtype', 'lineage_molecular_subtype', 'default_growth_pattern', 'model_manipulation', 'model_manipulation_details', 'patient_id', 'parent_depmap_id', 'cellosaurus_ncit_disease', 'cellosaurus_ncit_id', 'cellosaurus_issues']

---------

cellosaurus : ['cellosaurus_cell_line_name', 'cellosaurus_accession', 'secondary accession number(s)', 'synonyms', 'cross-references', 'references identifiers', 'web pages', 'comments', 'str profile data', 'diseases', 'species of origin', 'hierarchy', 'originate from same individual', 'sex of cell', 'age of donor at sampling', 'category', 'date (entry history)']

In [133]:
# Chceking the presese of the missing keys (CVCL_X507 & CVCL_V618) 
# Explode secondary accessions and match against rrid
secondary = df_cellosaurus_clean["secondary accession number(s)"].str.split("|").explode()
print(secondary[secondary.isin(["cvcl_x507", "cvcl_v618"])])

125217    cvcl_x507
Name: secondary accession number(s), dtype: str

In [134]:
print(df_cellosaurus_clean["cross-references"].head(5))

0                                 wikidata; q108819335
1                                 wikidata; q108819336
2    dbmhc; 48439 || ecacc; 94050311 || ihw; ihw093...
3                  rcb; rcb4635 || wikidata; q54422067
4                                  wikidata; q54422071
Name: cross-references, dtype: str

In [135]:
# Check 1 — secondary accession coverage
print(df_cellosaurus_clean["secondary accession number(s)"].notna().sum())
print(df_cellosaurus_clean["secondary accession number(s)"].head(3))

# Check 2 — cross-references format  
print(df_cellosaurus_clean["cross-references"].head(3))

# Check 3 — cellosaurus_ncit_id already in sample_info
print(df_sample_info_cleaned["cellosaurus_ncit_id"].notna().sum())

542
0    NaN
1    NaN
2    NaN
Name: secondary accession number(s), dtype: str
0                                 wikidata; q108819335
1                                 wikidata; q108819336
2    dbmhc; 48439 || ecacc; 94050311 || ihw; ihw093...
Name: cross-references, dtype: str
1747

In [136]:
# Explode secondary accessions → join to unmatched rrid
sec_acc = df_cellosaurus_clean[["cellosaurus_accession", "secondary accession number(s)"]].copy()
sec_acc = sec_acc.dropna(subset=["secondary accession number(s)"])
sec_acc["secondary_exploded"] = sec_acc["secondary accession number(s)"].str.split("||")
sec_acc = sec_acc.explode("secondary_exploded")
sec_acc["secondary_exploded"] = sec_acc["secondary_exploded"].str.strip()

# Debug raw value first
print(df_cellosaurus_clean.loc[125217, "secondary accession number(s)"])

# Likely delimiter is " || " not "||" — fix:
sec_acc["secondary_exploded"] = (
    sec_acc["secondary accession number(s)"]
    .str.split(r"\s*\|\|\s*", regex=True)   # handles any spacing
)
sec_acc = sec_acc.explode("secondary_exploded")
sec_acc["secondary_exploded"] = sec_acc["secondary_exploded"].str.strip().str.lower()


# Recover
recovered = df_sample_info_cleaned[
    df_sample_info_cleaned["rrid"].isin(sec_acc["secondary_exploded"])
].merge(sec_acc, left_on="rrid", right_on="secondary_exploded")

print("Recovered via secondary:", len(recovered))

cvcl_x507
Recovered via secondary: 11

In [137]:
# Cross-references format: "source; id || source; id"
def parse_cross_refs(ref_str):
    if pd.isna(ref_str): return {}
    pairs = {}
    for entry in ref_str.split("||"):
        if ";" in entry:
            source, id_ = entry.split(";", 1)
            pairs[source.strip().lower()] = id_.strip()
    return pairs

df_cellosaurus_clean["refs_parsed"] = df_cellosaurus_clean["cross-references"].apply(parse_cross_refs)

# Check all available source keys (look for depmap, cosmic, ccle)
all_sources = set()
df_cellosaurus_clean["refs_parsed"].apply(lambda d: all_sources.update(d.keys()))
print(sorted(all_sources)) 

# Extract depmap ACH IDs from cellosaurus cross-references
def extract_depmap(ref_str):
    if pd.isna(ref_str): return None
    for entry in ref_str.split("||"):
        if "depmap" in entry.lower() and ";" in entry:
            return entry.split(";", 1)[1].strip().lower()
    return None

df_cellosaurus_clean["depmap_xref"] = df_cellosaurus_clean["cross-references"].apply(extract_depmap)

print("Cellosaurus rows with depmap xref:", df_cellosaurus_clean["depmap_xref"].notna().sum())

# Direct bridge: cellosaurus → depmap_profiles (bypass sample_info gap)
bridge = df_cellosaurus_clean[["cellosaurus_accession", "depmap_xref"]].dropna()
recovered_depmap = bridge[bridge["depmap_xref"].isin(
    df_depmap_profiles_cleaned_pivoted["modelid"].str.lower()
)]
print("Cellosaurus → depmap_profiles direct match:", len(recovered_depmap))

['4dn', 'abcam', 'abcd', 'abm', 'addexbio', 'arrayexpress', 'atcc', 'bcgo', 'bcrc', 'bcrj', 'bei_resources', 'biogrid_orcs_cell_line', 'biosample', 'biosamples', 'bto', 'cancercelllines', 'cancertools', 'cba', 'cclv', 'ccrid', 'cctcc', 'cell_biolabs', 'cell_model_passport', 'cgh-db', 'chembl-cells', 'chembl-targets', 'cldb', 'clo', 'cls', 'colonatlas', 'coriell', 'cosmic', 'cosmic-clp', 'dbgap', 'dbmhc', 'depmap', 'dgrc', 'discoverx', 'dshb', 'dsmz', 'dsmzcelldive', 'ebisc', 'ecacc', 'efo', 'ega', 'encode', 'estdab', 'fcdi', 'fcs-free', 'flybase_cell_line', 'gdsc', 'genecopoeia', 'geo', 'hipsci', 'hivreagentprogram', 'horizon_discovery', 'hpscreg', 'iarc_tp53', 'ibrc', 'iclc', 'icldb', 'igrhcellid', 'igsr', 'ihw', 'imanis', 'innoprot', 'ipd-imgt/hla', 'iscr', 'izsler', 'jcrb', 'kcb', 'kclb', 'kerafast', 'kyinno', 'ligea', 'limore', 'lincs_hms', 'lincs_ldp', 'lonza', 'mccl', 'mesh', 'metabolights', 'millipore', 'mmrrc', 'ncbi_iran', 'nci-dtp', 'nhcdr', 'nihhesc', 'nises', 'nrfc', 'perkinelmer', 'pharmacodb', 'pride', 'progenetix', 'pubchem_cell_line', 'rcb', 'rockland', 'rscb', 'skip', 'sky/m-fish/cgh', 'slkbase', 'tkg', 'tngb', 'toku-e', 'ubigene', 'wicell', 'wikidata', 'ximbio']
Cellosaurus rows with depmap xref: 1893
Cellosaurus → depmap_profiles direct match: 1768

In [138]:
# Normalize both name columns
sample_names = df_sample_info_cleaned[df_sample_info_cleaned["rrid"].isna()].copy()
sample_names["name_norm"] = sample_names["cell_line_name"].str.strip().str.lower()

cvcl_names = df_cellosaurus_clean.copy()
cvcl_names["name_norm"] = cvcl_names["cellosaurus_cell_line_name"].str.strip().str.lower()

# Tier 2: exact name match
t2 = sample_names.merge(cvcl_names, on="name_norm")
print("Recovered via name match:", len(t2))

# Your concern is right — names are NOT guaranteed unique
name_counts = df_cellosaurus_clean["cellosaurus_cell_line_name"].str.strip().str.lower().value_counts()
duplicate_names = name_counts[name_counts > 1]
print("Duplicate names in cellosaurus:", len(duplicate_names))

# Only accept name match if it maps to exactly ONE cvcl
t2_safe = t2[~t2["name_norm"].isin(duplicate_names.index)]
print("Safe name recoveries:", len(t2_safe))

Recovered via name match: 8
Duplicate names in cellosaurus: 69
Safe name recoveries: 8

In [139]:
# 1. Confirm 3-tier cellosaurus join gives 1,831
# 2. Use cellosaurus depmap_xref as direct bridge
df_final = df_cellosaurus_clean[["cellosaurus_accession", "depmap_xref"]].merge(
    df_depmap_profiles_cleaned_pivoted,
    left_on="depmap_xref", right_on="modelid",
    how="outer"
)
print(df_final.shape)

# 3. Check remaining 9 unresolved in cellosaurus side
print(df_sample_info_cleaned[
    ~df_sample_info_cleaned["depmap_id"].isin(df_final["depmap_xref"])
]["cell_line_name"].tolist())

(152285, 10)
['a673stag2ko16', 'a673stag2ko45', 'a673stag2nt14', 'a673stag2nt23', 'myla', 'u-251 mg', 'hcc827gr', 'ss1a', 'gbm001', 'sc-1', 'a375_rpmi', 'rvh421_rpmi', 'nci-h292', nan, 'pl18', 'rh-1', 'ctv-1', nan]

In [140]:
# Parse cosmic & cell_model_passport from cellosaurus cross-references
def extract_xref(ref_str, source):
    if pd.isna(ref_str): return None
    for entry in ref_str.split("||"):
        if source in entry.lower() and ";" in entry:
            return entry.split(";", 1)[1].strip()
    return None

df_cellosaurus_clean["cosmic_xref"]   = df_cellosaurus_clean["cross-references"].apply(lambda x: extract_xref(x, "cosmic"))
df_cellosaurus_clean["sanger_xref"]   = df_cellosaurus_clean["cross-references"].apply(lambda x: extract_xref(x, "cell_model_passport"))

# Match against sample_info
cosmic_match  = df_sample_info_cleaned["cosmicid"].astype(str).isin(df_cellosaurus_clean["cosmic_xref"])
sanger_match  = df_sample_info_cleaned["sanger_model_id"].isin(df_cellosaurus_clean["sanger_xref"])

print("Recoverable via COSMIC :", cosmic_match.sum())
print("Recoverable via Sanger :", sanger_match.sum())

Recoverable via COSMIC : 859
Recoverable via Sanger : 1838

#### INSIGHTS FROM THE DATA RECOVERY METHODS

Table 1: Cellosaurus ↔ Sample_info
(via cellosaurus_accession ↔ rrid → sanger_model_id)

Dataset sizes → Cellosaurus: 152,231 rows, Sample_info: 1,840 rows (anchor)
Initial RRID exact match → 1,812 / 1,840 = 98.48% via rrid ↔ cellosaurus_accession
RRID null mapping → 22 / 1,840 = 1.20% have null rrid at source no accession recorded at data collection; unresolvable via RRID chain
Deprecated/secondary accession → 2 valid-format RRIDs (CVCL_X507, CVCL_V618) absent from primary dump; secondary accession explode recovered +1 (CVCL_X507), 1 permanently lost
Name-based fallback → safe exact name match (excluding 69 duplicate names in Cellosaurus) recovered +8 / 22 null-rrid rows
Sanger ID mapping → sanger_model_id ↔ cell_model_passport xref recovered 1,838 / 1,840 = 99.89% supersedes RRID as primary key
Hard floor loss → 2 / 1,840 = 0.11% both are NaN rows with no identifier; irrecoverable

Resolution summary → initial loss was 28 / 1,840 = 1.52% (28 unmatched); multi-tier recovery (secondary accession +1, name fallback +8, Sanger primary key +17) resolved 26 / 28 = 92.86% of initial loss → final matching rate improved from 98.48% → 99.89% (1,838 / 1,840) with only 2 irrecoverable NaN rows (0.11%) remaining.

Table 2: Sample_info ↔ DepMap Profiles
(via depmap_id ↔ modelid)

Dataset sizes → Sample_info: 1,840 rows, DepMap Profiles: 1,822 rows
Initial depmap_id exact match → 1,749 / 1,840 = 95.05% via depmap_id ↔ modelid
Directional loss → 91 depmap_ids in sample_info absent from profiles (4.95%); 73 modelids in profiles absent from sample_info — bidirectional gap
Root cause → pure DepMap release version mismatch — zero format issues (identical ach- prefix, length=10, zero nulls on both sides)
Cellosaurus xref bridge → depmap field in Cellosaurus cross-references yielded 1,893 entries; direct Cellosaurus → DepMap match = 1,768 / 1,822 = 97.04% — recovers +19 over initial join
Residual loss → 72 / 1,840 = 3.91% — cell lines present in sample_info but absent from both depmap_profiles and cellosaurus xref; version gap irrecoverable without unified DepMap release

Resolution summary → initial loss was 91 / 1,840 = 4.95% (91 unmatched from sample_info side); Cellosaurus depmap xref bridge recovered +19 records = 20.88% of initial loss resolved → final matching rate improved from 95.05% → 96.09% (1,768 / 1,840) with 72 irrecoverable records (3.91%) remaining due to release version gap.

> **Correction:** the "1,838/1,840 = 99.89%" Sanger figure above is inflated by a pandas gotcha - `.isin()` treats NaN as matching NaN, and 687/1,840 sample_info rows have a null sanger_model_id, so those were silently counted as "matched" against cellosaurus rows that also have a null sanger_xref. The real ceiling via Sanger alone (non-null values only) is ~1,150/1,840 (62.5%) - still the single strongest method, just not this high. See the corrected final numbers in "INSIGHTS FROM THE HARMONIZATION" below.

### Load the refernces

In [141]:
gene_lookup      = pd.read_parquet(os.path.join(REF, "gene_lookup.parquet"))
# loaded for reference/inspection only - this notebook intentionally
# does NOT use this as the base for cell_line_lookup below (see note in the
# next cell that rebuilds it from scratch).
cell_line_lookup = pd.read_parquet(os.path.join(REF, "cell_line_lookup.parquet"))

In [142]:
gene_lookup.head()

,ensg_id,hgnc_symbol,prev_symbols,alias_symbols,hgnc_id,biotype
0,ENSG00000121410,A1BG,NaN,NaN,HGNC:5,protein_coding
1,ENSG00000148584,A1CF,NaN,ACF|ASP|ACF64|ACF65|APOBEC1CF,HGNC:24086,protein_coding
2,ENSG00000175899,A2M,NaN,FWP007|S863-7|CPAMD5,HGNC:7,protein_coding
3,ENSG00000166535,A2ML1,CPAMD9,FLJ25179|p170,HGNC:23336,protein_coding
4,ENSG00000184389,A3GALT2,A3GALT2P,IGBS3S|IGB3S,HGNC:30005,protein_coding

In [143]:
cell_line_lookup.head()

,model_id,cell_line_name,stripped_cell_line_name,cvcl_accession,synonyms,rrid
0,ACH-000016,SLR 21,SLR21,CVCL_V607,SLR 21,CVCL_V607
1,ACH-000032,MHH-CALL-3,MHHCALL3,CVCL_0089,Mhh-Call 3|MHH cALL 3|MHH-CALL3|MHH-cALL3|MHHC...,CVCL_0089
2,ACH-000033,NCI-H1819,NCIH1819,CVCL_1497,H1819|H-1819|NCIH1819,CVCL_1497
3,ACH-000043,Hs 895.T,HS895T,CVCL_0993,Hs-895-T|Hs 895 T|Hs895.T|Hs895T|HS895T,CVCL_0993
4,ACH-000049,HEK TE,HEKTE,CVCL_WS59,HEK-TE|HEKTE,CVCL_WS59

#### TRACK A HARMONIZATION WITH THE LOOKUP TABLE

### Key to aggregate the tables:
- depmap_profile: modelid
- cellosaurus: cellosaurus_accession
- sample_info: depmap_id, rrid

In [144]:
df_cellosaurus_clean.columns

Index(['cellosaurus_cell_line_name', 'cellosaurus_accession',
       'secondary accession number(s)', 'synonyms', 'cross-references',
       'references identifiers', 'web pages', 'comments', 'str profile data',
       'diseases', 'species of origin', 'hierarchy',
       'originate from same individual', 'sex of cell',
       'age of donor at sampling', 'category', 'date (entry history)',
       'refs_parsed', 'depmap_xref', 'cosmic_xref', 'sanger_xref'],
      dtype='str')

In [145]:
df_depmap_profiles_cleaned_pivoted.columns

Index(['modelid', 'has_rna', 'has_wes', 'has_wgs', 'modelcondition_rna',
       'modelcondition_wes', 'modelcondition_wgs', 'weskit_wes'],
      dtype='str', name='datatype')

In [146]:
df_sample_info_cleaned.columns

Index(['depmap_id', 'cell_line_name', 'stripped_cell_line_name', 'ccle_name',
       'alias', 'cosmicid', 'sex', 'source', 'rrid', 'wtsi_master_cell_id',
       'sample_collection_site', 'primary_or_metastasis', 'primary_disease',
       'subtype', 'age', 'sanger_model_id', 'depmap_public_comments',
       'lineage', 'lineage_subtype', 'lineage_sub_subtype',
       'lineage_molecular_subtype', 'default_growth_pattern',
       'model_manipulation', 'model_manipulation_details', 'patient_id',
       'parent_depmap_id', 'cellosaurus_ncit_disease', 'cellosaurus_ncit_id',
       'cellosaurus_issues'],
      dtype='str')

In [147]:
cell_line_lookup.columns

Index(['model_id', 'cell_line_name', 'stripped_cell_line_name',
       'cvcl_accession', 'synonyms', 'rrid'],
      dtype='str')

### Track A: Cell Line Lookup Integration

- Architecture: hub-and-spoke.
    - Anchor  = sample_info            (owns canonical model_id, PK never null/dup)
    - Spoke 1 = cellosaurus            (resolved via 5-step cascade, NOT direct join)
    - Spoke 2 = depmap_profiles        (already ACH-keyed, direct left join bridge table for)

- Set theory per step:
    resolved_i   = unmatched_i * candidate_source_i
    unmatched_{i+1} = unmatched_i \\ resolved_i          (strictly shrinking, first-match-wins)

- Inputs expected in scope:
    df_sample_info_cleaned, df_cellosaurus_clean, df_depmap_profiles_cleaned_pivoted

In [148]:
# The cell line lookup is already loaded in the memory,so using the same rather than loading it again
# cell_line_lookup = pd.read_parquet(os.path.join(REF, "cell_line_lookup.parquet"))

cell_line_lookup_ces = cell_line_lookup.copy()

cell_line_lookup_ces["_resolution_step"] = pd.NA
cell_line_lookup_ces.loc[cell_line_lookup_ces["cvcl_accession"].notna(), "_resolution_step"] = "shipped_reference"

In [149]:
# unmatched_0 = all of cell_line_lookup (cvcl_accession is NA for every row)
ces = df_cellosaurus_clean.copy()
# Normalize case up front - rrid/accession casing is inconsistent at source

ces["cellosaurus_accession"] = ces["cellosaurus_accession"].astype(str).str.strip().str.upper()

def _normalize_cvcl(series: pd.Series) -> pd.Series:
    """Extract CVCL_XXXXXXX pattern from RRID/accession strings for robust matching."""
    return series.astype(str).str.upper().str.extract(r"(CVCL_\d+)", expand=False)

def _strip_name(series: pd.Series) -> pd.Series:
    return series.astype(str).str.upper().str.replace(r"[-_\s]", "", regex=True)

cell_line_lookup_ces["_rrid_cvcl"] = _normalize_cvcl(cell_line_lookup_ces["rrid"])

In [150]:

# ---- Step 2a: Sanger xref match (primary - highest-recall single method) ----
unmatched = cell_line_lookup_ces["cvcl_accession"].isna()
sanger_lookup = ces.dropna(subset=["sanger_xref"]).drop_duplicates("sanger_xref")
sanger_map = sanger_lookup.set_index("sanger_xref")[["cellosaurus_accession", "synonyms"]].to_dict("index")

merged = df_sample_info_cleaned.set_index("depmap_id")["sanger_model_id"].reindex(
    cell_line_lookup_ces.loc[unmatched, "model_id"]
).map(sanger_map)
merged.index = cell_line_lookup_ces.loc[unmatched].index
resolved_mask = unmatched & merged.notna()
cell_line_lookup_ces.loc[resolved_mask, "cvcl_accession"] = merged[merged.notna()].apply(lambda d: d["cellosaurus_accession"])
cell_line_lookup_ces.loc[resolved_mask, "synonyms"] = merged[merged.notna()].apply(lambda d: d["synonyms"])
cell_line_lookup_ces.loc[resolved_mask, "_resolution_step"] = "sanger_xref"

# ---- Step 2b: direct RRID match ----------------------------------------
unmatched = cell_line_lookup_ces["cvcl_accession"].isna()
lookup = ces.dropna(subset=["cellosaurus_accession"]).drop_duplicates("cellosaurus_accession")
merged = cell_line_lookup_ces.loc[unmatched, "_rrid_cvcl"].map(
    lookup.set_index("cellosaurus_accession", drop=False)[["cellosaurus_accession", "synonyms"]].to_dict("index")
)
resolved_mask = unmatched & merged.notna()
cell_line_lookup_ces.loc[resolved_mask, "cvcl_accession"] = merged[merged.notna()].apply(lambda d: d["cellosaurus_accession"])
cell_line_lookup_ces.loc[resolved_mask, "synonyms"] = merged[merged.notna()].apply(lambda d: d["synonyms"])
cell_line_lookup_ces.loc[resolved_mask, "_resolution_step"] = "direct_rrid"

# ---- Step 2c: secondary accession match --------------------------------
# Real delimiter is " || " (double pipe, optional spacing) - confirmed in the
# diagnostic exploration above (cell that debugged CVCL_X507 / CVCL_V618).
# The original cascade split on a single "|", which never matched anything
# and silently produced zero recoveries at this step.
unmatched = cell_line_lookup_ces["cvcl_accession"].isna()
sec = ces[["cellosaurus_accession", "secondary accession number(s)", "synonyms"]].copy()
sec["secondary accession number(s)"] = sec["secondary accession number(s)"].astype(str).str.split(r"\s*\|\|\s*", regex=True)
sec = sec.explode("secondary accession number(s)")
sec["secondary accession number(s)"] = sec["secondary accession number(s)"].str.strip().str.upper()
sec = sec.dropna(subset=["secondary accession number(s)"]).drop_duplicates("secondary accession number(s)")  # first match wins
sec_map = sec.set_index("secondary accession number(s)")[["cellosaurus_accession", "synonyms"]].to_dict("index")

merged = cell_line_lookup_ces.loc[unmatched, "_rrid_cvcl"].map(sec_map)
resolved_mask = unmatched & merged.notna()
cell_line_lookup_ces.loc[resolved_mask, "cvcl_accession"] = merged[merged.notna()].apply(lambda d: d["cellosaurus_accession"])
cell_line_lookup_ces.loc[resolved_mask, "synonyms"] = merged[merged.notna()].apply(lambda d: d["synonyms"])
cell_line_lookup_ces.loc[resolved_mask, "_resolution_step"] = "secondary_accession"

# ---- Step 2d: name match (exact, then stripped) ------------------------
unmatched = cell_line_lookup_ces["cvcl_accession"].isna()
name_lookup = ces.dropna(subset=["cellosaurus_cell_line_name"]).drop_duplicates("cellosaurus_cell_line_name")
name_map = name_lookup.set_index("cellosaurus_cell_line_name")[["cellosaurus_accession", "synonyms"]].to_dict("index")

merged = cell_line_lookup_ces.loc[unmatched, "cell_line_name"].map(name_map)
resolved_mask = unmatched & merged.notna()
cell_line_lookup_ces.loc[resolved_mask, "cvcl_accession"] = merged[merged.notna()].apply(lambda d: d["cellosaurus_accession"])
cell_line_lookup_ces.loc[resolved_mask, "synonyms"] = merged[merged.notna()].apply(lambda d: d["synonyms"])
cell_line_lookup_ces.loc[resolved_mask, "_resolution_step"] = "name_match"

unmatched = cell_line_lookup_ces["cvcl_accession"].isna()
name_lookup["_stripped_name"] = _strip_name(name_lookup["cellosaurus_cell_line_name"])
name_lookup_stripped = name_lookup.drop_duplicates("_stripped_name")
stripped_map = name_lookup_stripped.set_index("_stripped_name")[["cellosaurus_accession", "synonyms"]].to_dict("index")

merged = _strip_name(cell_line_lookup_ces.loc[unmatched, "stripped_cell_line_name"]).map(stripped_map)
resolved_mask = unmatched & merged.notna()
cell_line_lookup_ces.loc[resolved_mask, "cvcl_accession"] = merged[merged.notna()].apply(lambda d: d["cellosaurus_accession"])
cell_line_lookup_ces.loc[resolved_mask, "synonyms"] = merged[merged.notna()].apply(lambda d: d["synonyms"])
cell_line_lookup_ces.loc[resolved_mask, "_resolution_step"] = "stripped_name_match"

# ---- Step 2e: synonym fallback (exploded, first match wins) ------------
unmatched = cell_line_lookup_ces["cvcl_accession"].isna()
syn = ces[["cellosaurus_accession", "synonyms"]].copy()
syn["synonyms_exploded"] = syn["synonyms"].astype(str).str.split("|")
syn = syn.explode("synonyms_exploded")
syn["synonyms_exploded"] = syn["synonyms_exploded"].str.strip()
syn = syn.dropna(subset=["synonyms_exploded"]).drop_duplicates("synonyms_exploded")
syn_map = syn.set_index("synonyms_exploded")[["cellosaurus_accession", "synonyms"]].to_dict("index")

merged = cell_line_lookup_ces.loc[unmatched, "cell_line_name"].map(syn_map)
resolved_mask = unmatched & merged.notna()
cell_line_lookup_ces.loc[resolved_mask, "cvcl_accession"] = merged[merged.notna()].apply(lambda d: d["cellosaurus_accession"])
cell_line_lookup_ces.loc[resolved_mask, "synonyms"] = merged[merged.notna()].apply(lambda d: d["synonyms"])
cell_line_lookup_ces.loc[resolved_mask, "_resolution_step"] = "synonym_fallback"

cell_line_lookup_ces.drop(columns=["_rrid_cvcl"], inplace=True)

# ---- Step 3: attach remaining descriptive columns from Cellosaurus ----
# Do this once cvcl_accession is fully resolved (all cascade steps done).
payload_cols = [
    "cellosaurus_cell_line_name",      
    "cross-references",
    "references identifiers",
    "web pages",
    "comments",
    "str profile data",
    "diseases",
    "species of origin",
    "hierarchy",
    "originate from same individual",
    "sex of cell",
    "age of donor at sampling",
    "category",
    "date (entry history)",
    "refs_parsed",
    "depmap_xref",
    "cosmic_xref",
    "sanger_xref",
]

ces_payload = (
    ces.drop_duplicates("cellosaurus_accession")
       .set_index("cellosaurus_accession")[payload_cols]
)

cell_line_lookup_ces = cell_line_lookup_ces.join(
    ces_payload,
    on="cvcl_accession",
    how="left",
    rsuffix="_ces",   # only kicks in if a name collides
)

# ---- Unmapped log - cellosaurus side ------------------------------------
unmapped_cellosaurus = cell_line_lookup_ces.loc[
    cell_line_lookup_ces["cvcl_accession"].isna(), ["model_id"]
].copy()
unmapped_cellosaurus["dataset"] = "cellosaurus"
unmapped_cellosaurus["resolution_step_reached"] = "cascade_exhausted"
unmapped_cellosaurus["reason"] = "no match at RRID / secondary accession / name / synonym / sanger_xref"
unmapped_cellosaurus = unmapped_cellosaurus.rename(columns={"model_id": "original_value"})[
    ["original_value", "dataset", "resolution_step_reached", "reason"]
]

print("Unmapped cellosaurus rows:", len(unmapped_cellosaurus))

Unmapped cellosaurus rows: 14

In [151]:
# lookup table for depmap profile 
df_depmap_profiles_cleaned_pivoted = df_depmap_profiles_cleaned_pivoted.rename(columns={"modelid": "model_id"})
df_depmap_profiles_cleaned_pivoted["model_id"] = df_depmap_profiles_cleaned_pivoted["model_id"].str.upper()

cell_line_lookup_dep = cell_line_lookup.copy().merge(
    df_depmap_profiles_cleaned_pivoted,
    on="model_id",
    how="left",
    indicator=True,
)

# Orphaned direction: profiles rows whose model_id has no home in cell_line_lookup.
unmapped_depmap_profiles = df_depmap_profiles_cleaned_pivoted.loc[
    ~df_depmap_profiles_cleaned_pivoted["model_id"].isin(cell_line_lookup["model_id"])
].copy()
unmapped_depmap_profiles["dataset"] = "depmap_profiles"
unmapped_depmap_profiles["resolution_step_reached"] = "direct_join"
unmapped_depmap_profiles["reason"] = "model_id not present in cell_line_lookup.model_id"
unmapped_depmap_profiles = unmapped_depmap_profiles.rename(columns={"model_id": "original_value"})[
    ["original_value", "dataset", "resolution_step_reached", "reason"]
]

cell_line_lookup_dep.drop(columns=["_merge"], inplace=True)

print("cell_line_lookup:", len(cell_line_lookup), "rows")
print("Unmapped depmap_profiles rows:", len(unmapped_depmap_profiles))

cell_line_lookup: 1840 rows
Unmapped depmap_profiles rows: 73

In [152]:
# cell line lookup for the sample info 
df_sample_info_cleaned["depmap_id"] = df_sample_info_cleaned["depmap_id"].str.upper()
df_sample_info_cleaned.rename(columns={"depmap_id": "model_id"}, inplace=True)

cell_line_lookup_sam = cell_line_lookup.copy().merge(
    df_sample_info_cleaned, 
    on="model_id",
    how="left",
    indicator=True
)

# unmapped logs on sample_info 
unmapped_sample_info = df_sample_info_cleaned.loc[
    ~df_sample_info_cleaned["model_id"].isin(cell_line_lookup["model_id"])
].copy()
unmapped_sample_info["dataset"] = "sample_info"
unmapped_sample_info["resolution_step_reached"] = "direct_join"
unmapped_sample_info["reason"] = "model_id not present in cell_line_lookup.model_id"
unmapped_sample_info = unmapped_sample_info.rename(columns={"model_id": "original_value"})[
    ["original_value", "dataset", "resolution_step_reached", "reason"]
]

print("unmapped rows in sample_info:", len(unmapped_sample_info))

unmapped rows in sample_info: 0

In [153]:
# Cell line lookup for the cellosaurus mapped 
cell_line_lookup_ces.head()

,model_id,cell_line_name,stripped_cell_line_name,cvcl_accession,synonyms,rrid,_resolution_step,cellosaurus_cell_line_name,cross-references,references identifiers,...,hierarchy,originate from same individual,sex of cell,age of donor at sampling,category,date (entry history),refs_parsed,depmap_xref,cosmic_xref,sanger_xref
0,ACH-000016,SLR 21,SLR21,CVCL_V607,SLR 21,CVCL_V607,shipped_reference,slr21,biosample; samn10988415 || cancercelllines; cv...,pubmed=12907621; || pubmed=19470766; || pubmed...,...,NaN,NaN,sex unspecified,age unspecified,cancer cell line,created: 16-04-14; last updated: 05-10-23; ver...,"{'biosample': 'samn10988415', 'cancercelllines...",ach-000016,2520630,sidm01862
1,ACH-000032,MHH-CALL-3,MHHCALL3,CVCL_0089,Mhh-Call 3|MHH cALL 3|MHH-CALL3|MHH-cALL3|MHHC...,CVCL_0089,shipped_reference,mhh-call-3,clo; clo_0007716 || arrayexpress; e-mtab-2770 ...,doi=10.1016/b978-0-12-221970-2.50457-5; || pub...,...,NaN,NaN,female,11y,cancer cell line,created: 04-04-12; last updated: 30-01-24; ver...,"{'clo': 'clo_0007716', 'arrayexpress': 'e-mtab...",ach-000032,1281374,sidm01693
2,ACH-000033,NCI-H1819,NCIH1819,CVCL_1497,H1819|H-1819|NCIH1819,CVCL_1497,shipped_reference,nci-h1819,clo; clo_0008021 || atcc; crl-5897 || biosampl...,pubmed=8806092; || pubmed=9559342; || pubmed=1...,...,NaN,cvcl_e099 ! nci-bl1819 || cvcl_1488 ! nci-h1693,female,55y,cancer cell line,created: 04-04-12; last updated: 30-01-24; ver...,"{'clo': 'clo_0008021', 'atcc': 'crl-5897', 'bi...",ach-000033,877247,sidm01674
3,ACH-000043,Hs 895.T,HS895T,CVCL_0993,Hs-895-T|Hs 895 T|Hs895.T|Hs895T|HS895T,CVCL_0993,shipped_reference,hs 895.t,clo; clo_0004200 || efo; efo_0006593 || arraye...,doi=10.1101/166199; || pubmed=20215515; || pub...,...,NaN,cvcl_0992 ! hs 895.sk,female,48y,undefined cell line type,created: 04-04-12; last updated: 05-10-23; ver...,"{'clo': 'clo_0004200', 'efo': 'efo_0006593', '...",ach-000043,NaN,sidm01743
4,ACH-000049,HEK TE,HEKTE,CVCL_WS59,HEK-TE|HEKTE,CVCL_WS59,shipped_reference,hek te,clo; clo_0037298 || biosample; samn10988406 ||...,pubmed=31068700;,...,NaN,NaN,NaN,NaN,transformed cell line,created: 05-07-19; last updated: 05-10-23; ver...,"{'clo': 'clo_0037298', 'biosample': 'samn10988...",ach-000049,NaN,sidm01723

In [154]:
# cell line lookup overview 
cell_line_lookup_dep.head()

,model_id,cell_line_name,stripped_cell_line_name,cvcl_accession,synonyms,rrid,has_rna,has_wes,has_wgs,modelcondition_rna,modelcondition_wes,modelcondition_wgs,weskit_wes
0,ACH-000016,SLR 21,SLR21,CVCL_V607,SLR 21,CVCL_V607,True,False,False,mc-000016-0cgg,NaN,NaN,NaN
1,ACH-000032,MHH-CALL-3,MHHCALL3,CVCL_0089,Mhh-Call 3|MHH cALL 3|MHH-CALL3|MHH-cALL3|MHHC...,CVCL_0089,True,True,False,mc-000032-b8um,mc-000032-b8um,NaN,agilent
2,ACH-000033,NCI-H1819,NCIH1819,CVCL_1497,H1819|H-1819|NCIH1819,CVCL_1497,True,False,False,mc-000033-96oj,NaN,NaN,NaN
3,ACH-000043,Hs 895.T,HS895T,CVCL_0993,Hs-895-T|Hs 895 T|Hs895.T|Hs895T|HS895T,CVCL_0993,True,True,False,mc-000043-0ycn,mc-000043-0ycn,NaN,agilent
4,ACH-000049,HEK TE,HEKTE,CVCL_WS59,HEK-TE|HEKTE,CVCL_WS59,True,False,False,mc-000049-k0ty,NaN,NaN,NaN

In [155]:
cell_line_lookup_sam.head()

,model_id,cell_line_name_x,stripped_cell_line_name_x,cvcl_accession,synonyms,rrid_x,cell_line_name_y,stripped_cell_line_name_y,ccle_name,alias,...,lineage_molecular_subtype,default_growth_pattern,model_manipulation,model_manipulation_details,patient_id,parent_depmap_id,cellosaurus_ncit_disease,cellosaurus_ncit_id,cellosaurus_issues,_merge
0,ACH-000016,SLR 21,SLR21,CVCL_V607,SLR 21,CVCL_V607,slr 21,slr21,slr21_kidney,NaN,...,NaN,NaN,NaN,NaN,pt-jnarlb,NaN,clear cell renal cell carcinoma,c4033,NaN,both
1,ACH-000032,MHH-CALL-3,MHHCALL3,CVCL_0089,Mhh-Call 3|MHH cALL 3|MHH-CALL3|MHH-cALL3|MHHC...,CVCL_0089,mhh-call-3,mhhcall3,mhhcall3_haematopoietic_and_lymphoid_tissue,NaN,...,NaN,NaN,NaN,NaN,pt-p2koyi,NaN,childhood b acute lymphoblastic leukemia,c9140,NaN,both
2,ACH-000033,NCI-H1819,NCIH1819,CVCL_1497,H1819|H-1819|NCIH1819,CVCL_1497,nci-h1819,ncih1819,ncih1819_lung,NaN,...,NaN,NaN,NaN,NaN,pt-9p1wqv,NaN,lung adenocarcinoma,c3512,NaN,both
3,ACH-000043,Hs 895.T,HS895T,CVCL_0993,Hs-895-T|Hs 895 T|Hs895.T|Hs895T|HS895T,CVCL_0993,hs 895.t,hs895t,hs895t_fibroblast,NaN,...,NaN,2d: adherent,NaN,NaN,pt-rtuvzq,NaN,melanoma,c3224,NaN,both
4,ACH-000049,HEK TE,HEKTE,CVCL_WS59,HEK-TE|HEKTE,CVCL_WS59,hek te,hekte,hekte_kidney,NaN,...,NaN,NaN,immortalized,NaN,pt-qwyygr,NaN,NaN,NaN,no information is available about this cell li...,both

In [156]:
# unmapped log details of cellosaurus 
unmapped_cellosaurus.head()

,original_value,dataset,resolution_step_reached,reason
105,ACH-001007,cellosaurus,cascade_exhausted,no match at RRID / secondary accession / name ...
106,ACH-001008,cellosaurus,cascade_exhausted,no match at RRID / secondary accession / name ...
107,ACH-001009,cellosaurus,cascade_exhausted,no match at RRID / secondary accession / name ...
108,ACH-001010,cellosaurus,cascade_exhausted,no match at RRID / secondary accession / name ...
135,ACH-001134,cellosaurus,cascade_exhausted,no match at RRID / secondary accession / name ...

In [157]:
# unmapped details of the depmap profile 
unmapped_depmap_profiles.head()

datatype,original_value,dataset,resolution_step_reached,reason
1195,ACH-001437,depmap_profiles,direct_join,model_id not present in cell_line_lookup.model_id
1196,ACH-001438,depmap_profiles,direct_join,model_id not present in cell_line_lookup.model_id
1210,ACH-001481,depmap_profiles,direct_join,model_id not present in cell_line_lookup.model_id
1221,ACH-001508,depmap_profiles,direct_join,model_id not present in cell_line_lookup.model_id
1244,ACH-001537,depmap_profiles,direct_join,model_id not present in cell_line_lookup.model_id

### INSIGHTS FROM THE HARMONIZATION

- Comprehensive Tracking: The dual unmapped logging approach provides visibility into both directions of the mapping problem - what could not be mapped to
  reference standards AND what reference data could not be integrated.
- Data Quality Indicators: The 33 unmapped cell lines (1.79%) may represent:
    - Novel or poorly characterized cell lines
    - Data quality issues in source identifiers
    - Limitations in current cross-reference databases
    - Cell lines requiring manual curation
- Process Transparency: By recording the specific reason and resolution step reached for each unmapped record, the process enables targeted follow-up and continuous improvement of the matching algorithms.
- Integration Completeness: The success rate (98.21%, 1,807/1,840) demonstrates the effectiveness of the multi-identifier cascading approach. Resolution
  breakdown: sanger_xref 1,151, direct_rrid 469, name_match 123, stripped_name_match 62, synonym_fallback 2 - Sanger cross-reference matching (run first,
  per the reordered cascade) is the single most productive strategy, consistent with the diagnostic exploration once its inflated 99.89% figure is corrected
  (see note above) to the real ~62.5% ceiling for that method alone.
- These numbers reflect a verified, actually-executed run of this notebook end-to-end (not the earlier draft figures of 68 unmapped / 96.3%, which predated
  the delimiter fix, case-normalization fix, and cascade reordering applied above).

In [158]:
# log the directory - save alongside this notebook (src/Track - A/), same
# location the existing trackA_*_unmapped_log.csv files already live in
logs_dir = _notebook_dir
os.makedirs(logs_dir, exist_ok=True)

# Save unmapped cellosaurus log
cellosaurus_log_path = os.path.join(logs_dir, 'trackA_cellosaurus_unmapped_log.csv')
print(cellosaurus_log_path)
unmapped_cellosaurus.to_csv(cellosaurus_log_path, index=False)

# Save unmapped depmap profiles log
depmap_log_path = os.path.join(logs_dir, 'trackA_depmap_profiles_unmapped_log.csv')
print(depmap_log_path)
unmapped_depmap_profiles.to_csv(depmap_log_path, index=False)

print("saved the logged files !!!")

D:\MSc Data Science\Dissertation\AstraZeneca\UoB-GeneTraceAI-25-26\trackA_cellosaurus_unmapped_log.csv
D:\MSc Data Science\Dissertation\AstraZeneca\UoB-GeneTraceAI-25-26\trackA_depmap_profiles_unmapped_log.csv
saved the logged files !!!

In [159]:
# Store the cell_line_lookup_dep as parquet under cleaned_track_data/,
# matching the convention used by the other tracks' cleaned outputs
harmonization_path = os.path.join(PROJECT_ROOT, "cleaned_track_data")
os.makedirs(harmonization_path, exist_ok=True)

In [160]:
# Save the Cell line lookup for the cellosaurus mapped 
# save the cell_line_lookup_dep in Cellosaurus_harmonization_path.parquet
Cellosaurus_harmonization_path = os.path.join(harmonization_path, 'Cellosaurus.parquet')
print(Cellosaurus_harmonization_path)
cell_line_lookup_ces.to_parquet(Cellosaurus_harmonization_path, index=False)

D:\MSc Data Science\Dissertation\AstraZeneca\UoB-GeneTraceAI-25-26\cleaned_track_data\Cellosaurus.parquet

In [166]:
# save the cell_line_lookup_dep in dep_harmonization.parquet
dep_harmonization_path = os.path.join(harmonization_path, 'depmap_profile.parquet')
print(dep_harmonization_path)
cell_line_lookup_dep.to_parquet(dep_harmonization_path, index=False)

D:\MSc Data Science\Dissertation\AstraZeneca\UoB-GeneTraceAI-25-26\cleaned_track_data\depmap_profile.parquet

In [164]:
# save the cell_line_lookup_dep in dep_harmonization.parquet
sam_harmonization_path = os.path.join(harmonization_path, 'sample_info.parquet')
print(sam_harmonization_path)
cell_line_lookup_sam.to_parquet(sam_harmonization_path, index=False)

D:\MSc Data Science\Dissertation\AstraZeneca\UoB-GeneTraceAI-25-26\cleaned_track_data\sample_info.parquet

In [3]:
cl_lkp = pd.read_parquet("reference/cell_line_lookup.parquet")

cl_lkp.head()

,model_id,primary_cvcl,canonical_name,rrid,is_multi_model,cvcl_dup_group_size,has_depmap,gap_class,gap_status,cell_line_name,n_model_ids,diseases,species_of_origin,sex,age_at_sampling,category,parent_hierarchy,comments,secondary_accessions
0,ACH-000004,cvcl_0001,hel,cvcl_0001,False,1.0,True,False,NaN,hel,1.0,ncit; c7152; erythroleukemia || ordo; orphanet...,ncbi_taxid=9606; ! homo sapiens (human),male,30y,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1,ACH-000002,cvcl_0002,hl-60,cvcl_0002,False,1.0,True,False,NaN,hl-60,1.0,ncit; c9154; adult acute myeloid leukemia || o...,ncbi_taxid=9606; ! homo sapiens (human),female,36y,cancer cell line,NaN,group: space-flown cell line (cellonaut). || p...,NaN
2,ACH-000551,cvcl_0004,k-562,cvcl_0004,False,1.0,True,False,NaN,k-562,1.0,ncit; c9110; blast phase chronic myelogenous l...,ncbi_taxid=9606; ! homo sapiens (human),female,53y,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
3,ACH-000294,cvcl_0005,nb4,cvcl_0005,False,1.0,True,False,NaN,nb-4,1.0,ncit; c3182; acute promyelocytic leukemia with...,ncbi_taxid=9606; ! homo sapiens (human),female,23y,cancer cell line,NaN,group: patented cell line. || part of: cancer ...,NaN
4,ACH-000146,cvcl_0006,thp-1,cvcl_0006,False,1.0,True,False,NaN,thp-1,1.0,ncit; c9163; childhood acute monocytic leukemi...,ncbi_taxid=9606; ! homo sapiens (human),male,1y,cancer cell line,NaN,group: space-flown cell line (cellonaut). || p...,NaN

In [5]:
cl_lkp.shape

(1840, 19)

In [22]:
un_ent = pd.read_parquet("reference/union_lookup_entity.parquet")

un_ent.tail(20)

,primary_cvcl,model_id_set,cell_line_names,n_model_ids,is_multi_model,rrid,has_depmap,gap_class,canonical_name,diseases,species_of_origin,sex,age_at_sampling,category,parent_hierarchy,comments,secondary_accessions
1792,cvcl_wu66,[ACH-001814],[os252],1,False,cvcl_wu66,True,False,os252,ncit; c9145; osteosarcoma || ordo; orphanet_66...,ncbi_taxid=9606; ! homo sapiens (human),male,NaN,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1793,cvcl_wu67,[ACH-001796],[95t1000],1,False,cvcl_wu67,True,False,95t1000,ncit; c6505; atypical lipomatous tumor/well di...,ncbi_taxid=9606; ! homo sapiens (human),male,48y,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1794,cvcl_wu91,[ACH-001280],[scs-214],1,False,cvcl_wu91,True,False,scs214,ncit; c3400; synovial sarcoma || ordo; orphane...,ncbi_taxid=9606; ! homo sapiens (human),NaN,NaN,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1795,cvcl_x481,[ACH-002089],[201t],1,False,cvcl_x481,True,False,201t,ncit; c3512; lung adenocarcinoma,ncbi_taxid=9606; ! homo sapiens (human),male,68y,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1796,cvcl_x483,[ACH-002092],[chsa0011],1,False,cvcl_x483,True,False,chsa0011,ncit; c2946; chondrosarcoma || ordo; orphanet_...,ncbi_taxid=9606; ! homo sapiens (human),male,NaN,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1797,cvcl_x484,[ACH-002093],[chsa0108],1,False,cvcl_x484,True,False,chsa0108,ncit; c2946; chondrosarcoma || ordo; orphanet_...,ncbi_taxid=9606; ! homo sapiens (human),male,NaN,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1798,cvcl_x485,[ACH-002094],[chsa8926],1,False,cvcl_x485,True,False,chsa8926,ncit; c2946; chondrosarcoma || ordo; orphanet_...,ncbi_taxid=9606; ! homo sapiens (human),male,NaN,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1799,cvcl_x486,[ACH-002101],[emc-bac-1],1,False,cvcl_x486,True,False,emc-bac-1,ncit; c3512; lung adenocarcinoma,ncbi_taxid=9606; ! homo sapiens (human),male,age unspecified,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1800,cvcl_x487,[ACH-002102],[emc-bac-2],1,False,cvcl_x487,True,False,emc-bac-2,ncit; c3512; lung adenocarcinoma,ncbi_taxid=9606; ! homo sapiens (human),sex unspecified,age unspecified,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1801,cvcl_x504,[ACH-001677],[u-2904],1,False,cvcl_x504,True,False,u-2904,ncit; c8851; diffuse large b-cell lymphoma || ...,ncbi_taxid=9606; ! homo sapiens (human),male,59y,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1802,cvcl_x505,[ACH-002167],[ncc010],1,False,cvcl_x505,True,False,ncc010,ncit; c9385; renal cell carcinoma || ordo; orp...,ncbi_taxid=9606; ! homo sapiens (human),male,age unspecified,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1803,cvcl_x506,[ACH-002168],[ncc021],1,False,cvcl_x506,True,False,ncc021,ncit; c9385; renal cell carcinoma || ordo; orp...,ncbi_taxid=9606; ! homo sapiens (human),sex unspecified,age unspecified,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1804,cvcl_x508,[ACH-002306],[sts-0421],1,False,cvcl_x508,True,False,sts-0421,ncit; c4004; gastric adenocarcinoma,ncbi_taxid=9606; ! homo sapiens (human),NaN,NaN,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1805,cvcl_x981,[ACH-001022],[cbagpn],1,False,cvcl_x981,True,False,agpn,ncit; c3716; primitive neuroectodermal tumor,ncbi_taxid=9606; ! homo sapiens (human),female,NaN,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1806,cvcl_y019,[ACH-002475],[hap1],1,False,cvcl_y019,True,False,hap1,"ncit; c3174; chronic myelogenous leukemia, bcr...",ncbi_taxid=9606; ! homo sapiens (human),male,40y,cancer cell line,cvcl_a426 ! kbm-7,group: haploid karyotype cell line. || part of...,NaN
1807,cvcl_y545,[ACH-001634],[pga-1],1,False,cvcl_y545,True,False,pga-1,ncit; c3163; chronic lymphocytic leukemia || o...,ncbi_taxid=9606; ! homo sapiens (human),male,age unspecified,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1808,cvcl_y547,[ACH-001520],[hg-3],1,False,cvcl_y547,True,False,hg-3,ncit; c3163; chronic lymphocytic leukemia || o...,ncbi_taxid=9606; ! homo sapiens (human),male,70y,transformed cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1809,cvcl_y548,[ACH-001484],[ci],1,False,cvcl_y548,True,False,ci,ncit; c3163; chronic lymphocytic leukemia || o...,ncbi_taxid=9606; ! homo sapiens (human),female,47y,transformed cell line,cvcl_0d73 ! cii,part of: cancer dependency map project (depmap...,NaN
1810,cvcl_y549,[ACH-001707],[wa-osel],1,False,cvcl_y549,True,False,wa-osel,ncit; c3163; chronic lymphocytic leukemia || o...,ncbi_taxid=9606; ! homo sapiens (human),male,adult,transformed cell line,NaN,part of: cancer dependency map project (depmap...,NaN
1811,cvcl_yu13,[ACH-002800],[ncc-mpnst2-c1],1,False,cvcl_yu13,True,False,ncc-mpnst2-c1,ncit; c3798; malignant peripheral nerve sheath...,ncbi_taxid=9606; ! homo sapiens (human),male,54y,cancer cell line,NaN,part of: cancer dependency map project (depmap...,NaN

In [33]:
un_ent.groupby(by="primary_cvcl")["model_id_set"].apply(len)

primary_cvcl
cvcl_0001    1
cvcl_0002    1
cvcl_0004    1
cvcl_0005    1
cvcl_0006    1
            ..
cvcl_y545    1
cvcl_y547    1
cvcl_y548    1
cvcl_y549    1
cvcl_yu13    1
Name: model_id_set, Length: 1812, dtype: int64

In [30]:
un_ent.loc[un_ent["model_id_set"].apply(len) > 1, "primary_cvcl"]

33     cvcl_0041
333    cvcl_1122
358    cvcl_1150
531    cvcl_1337
790    cvcl_1637
810    cvcl_1658
Name: primary_cvcl, dtype: str

In [27]:
cl_lkp[cl_lkp["is_multi_model"] == True][
    ["model_id", "primary_cvcl", "canonical_name"]
]

       model_id primary_cvcl canonical_name
33   ACH-000833    cvcl_0041           rh30
34   ACH-001189    cvcl_0041           rh30
334  ACH-001041    cvcl_1122          chl-1
335  ACH-001024    cvcl_1122          chl-1
360  ACH-002222    cvcl_1150          ctv-1
361  ACH-001737    cvcl_1150          ctv-1
534  ACH-001543    cvcl_1337         kosc-2
535  ACH-002260    cvcl_1337         kosc-2
794  ACH-000093    cvcl_1637     panc 05.04
795  ACH-002185    cvcl_1637     panc 05.04
815  ACH-000499    cvcl_1658           ew-8
816  ACH-002194    cvcl_1658           ew-8

In [28]:
# This is the proof — should return 6 CVCLs each appearing twice
cl_lkp.groupby("primary_cvcl")["model_id"].count().sort_values(ascending=False).head(10)

primary_cvcl
cvcl_1337    2
cvcl_1637    2
cvcl_1122    2
cvcl_0041    2
cvcl_1150    2
cvcl_1658    2
cvcl_0001    1
cvcl_0002    1
cvcl_0004    1
cvcl_0005    1
Name: model_id, dtype: int64

In [29]:
# CORRECT — group into sets, preserve all model_ids per CVCL
reverse_map = (
    cl_lkp.groupby("primary_cvcl")["model_id"]
    .apply(set)
    .to_dict()
)

# Verify the one-to-many is preserved
for cvcl, model_ids in reverse_map.items():
    if len(model_ids) > 1:
        print(f"{cvcl} → {model_ids}")
# Expect: 6 CVCLs each showing {ACH-xxxxxx, ACH-yyyyyy}

cvcl_0041 → {'ACH-000833', 'ACH-001189'}
cvcl_1122 → {'ACH-001041', 'ACH-001024'}
cvcl_1150 → {'ACH-002222', 'ACH-001737'}
cvcl_1337 → {'ACH-001543', 'ACH-002260'}
cvcl_1637 → {'ACH-002185', 'ACH-000093'}
cvcl_1658 → {'ACH-000499', 'ACH-002194'}