In [6]:
from pathlib import Path
import pandas as pd

PARQUET_CLEAN = Path("/Users/trivenidhamdhere/Documents/MSc Data Science/MSc Dissertation - AZ/cleaned_track_data")

tables = {
    p.stem: pd.read_parquet(p, engine="fastparquet")
    for p in sorted(PARQUET_CLEAN.glob("*.parquet"))
}

# sanity check
for name, df in tables.items():
    print(f"{name:25s} {df.shape}")

Cellosaurus               (1840, 49)
depmap_expr_gene_resolved_STAGING (28977585, 3)
depmap_profile            (1840, 13)
fusions_gene_level        (145842, 8)
geo_expr_resolved         (36676472, 4)
geo_info                  (3267, 25)
hpa_desc_resolved         (1104, 8)
hpa_rna_resolved          (21244502, 7)
metabolomics              (928, 227)
mirna_model_level         (695832, 4)
mutations_collapsed       (636568, 13)
mutations_variant_detail  (708796, 18)
proteomics                (375, 10130)
sample_info               (1840, 35)
signatures_model_level    (1955, 7)

In [7]:
cellosaurus                = tables["Cellosaurus"]
depmap_expr_gene_resolved  = tables["depmap_expr_gene_resolved_STAGING"]
depmap_profile             = tables["depmap_profile"]
fusions_gene_level         = tables["fusions_gene_level"]
geo_expr_resolved          = tables["geo_expr_resolved"]
geo_info                   = tables["geo_info"]
hpa_desc_resolved          = tables["hpa_desc_resolved"]
hpa_rna_resolved           = tables["hpa_rna_resolved"]
metabolomics               = tables["metabolomics"]
mirna_model_level          = tables["mirna_model_level"]
mutations_collapsed        = tables["mutations_collapsed"]
mutations_variant_detail   = tables["mutations_variant_detail"]
proteomics                 = tables["proteomics"]
sample_info                = tables["sample_info"]
signatures_model_level     = tables["signatures_model_level"]

In [8]:
cellosaurus

,model_id,cell_line_name,cvcl_accession,synonyms,rrid,_resolution_step,cellosaurus_cell_line_name,cross-references,references identifiers,web pages,...,refs_parsed.efo,refs_parsed.ega,refs_parsed.bto,refs_parsed.chembl-cells,refs_parsed.chembl-targets,refs_parsed.lincs_ldp,refs_parsed.pubchem_cell_line,refs_parsed.cosmic-clp,refs_parsed.gdsc,refs_parsed.biogrid_orcs_cell_line
0,ach-000016,slr21,cvcl_v607,slr 21,cvcl_v607,shipped_reference,slr21,biosample; samn10988415 || cancercelllines; cv...,pubmed=12907621; || pubmed=19470766; || pubmed...,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,ach-000032,mhhcall3,cvcl_0089,mhh-call 3|mhh call 3|mhh-call3|mhh-call3|mhhc...,cvcl_0089,shipped_reference,mhh-call-3,clo; clo_0007716 || arrayexpress; e-mtab-2770 ...,doi=10.1016/b978-0-12-221970-2.50457-5; || pub...,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,ach-000033,ncih1819,cvcl_1497,h1819|h-1819|ncih1819,cvcl_1497,shipped_reference,nci-h1819,clo; clo_0008021 || atcc; crl-5897 || biosampl...,pubmed=8806092; || pubmed=9559342; || pubmed=1...,https://tcpaportal.org/mclp/,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,ach-000043,hs895t,cvcl_0993,hs-895-t|hs 895 t|hs895.t|hs895t|hs895t,cvcl_0993,shipped_reference,hs 895.t,clo; clo_0004200 || efo; efo_0006593 || arraye...,doi=10.1101/166199; || pubmed=20215515; || pub...,<NA>,...,efo_0006593,egas00001000610,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,ach-000049,hekte,cvcl_ws59,hek-te|hekte,cvcl_ws59,shipped_reference,hek te,clo; clo_0037298 || biosample; samn10988406 ||...,pubmed=31068700;,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1835,ach-002393,croap3,cvcl_1810,cro-ap/3|croap3|ap3,cvcl_1810,shipped_reference,cro-ap3,bto; bto:0002725 || clo; clo_0002618 || biosam...,doi=10.1016/b978-0-12-221970-2.50457-5; || pub...,http://www.cells-talk.com/index.php/page/copel...,...,<NA>,<NA>,bto:0002725,<NA>,<NA>,<NA>,<NA>,1297440,1297440,<NA>
1836,ach-002394,geo,cvcl_0271,geo|hct-geo|hct geo,cvcl_0271,shipped_reference,geo,bto; bto:0002892 || mccl; mcc:0000162 || cance...,pubmed=2835152; || pubmed=3349466; || pubmed=6...,<NA>,...,<NA>,<NA>,bto:0002892,<NA>,<NA>,<NA>,<NA>,2164691,2164691,<NA>
1837,ach-002395,huh6clone5,cvcl_1296,huh-6 clone-5|huh-6 clone 5|huh-6 clone 5|huh-...,cvcl_1296,shipped_reference,huh-6 clone 5,arrayexpress; e-mtab-783 || biosample; samn034...,pubmed=57894; || pubmed=6161524; || pubmed=629...,<NA>,...,<NA>,<NA>,<NA>,chembl3308701,<NA>,<NA>,<NA>,907070,907070,<NA>
1838,ach-002396,sarc9371,cvcl_5g89,sarc9371,cvcl_5g89,shipped_reference,sarc9371,cancercelllines; cvcl_5g89 || cell_model_passp...,pubmed=30894373;,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1303910,1303910,<NA>
1839,ach-002397,kmhdash2,cvcl_s641,kmhdash2|kmh2,cvcl_s641,shipped_reference,kmh-2,clo; clo_0037155 || arrayexpress; e-mtab-3610 ...,pubmed=11686581; || pubmed=20215515; || pubmed...,<NA>,...,<NA>,egas00001000978,<NA>,<NA>,<NA>,lcl-1684,<NA>,1298167,1298167,<NA>

In [9]:
import pandas as pd

def lower_all(df):
    """
    Lowercase column names and all string values in a DataFrame.
    Non-string columns (numeric, bool, datetime) are left untouched.
    Returns a new DataFrame; does not modify in place.
    """
    df = df.copy()

    # lowercase column names
    df.columns = [str(c).lower() for c in df.columns]

    # lowercase string values only, column by column
    for col in df.columns:
        if pd.api.types.is_object_dtype(df[col]) or pd.api.types.is_string_dtype(df[col]):
            df[col] = df[col].str.lower()

    return df

In [10]:
import re

# 1. lower everything (col names + string values)
#cellosaurus = lower_all(cellosaurus)

# 2. drop the old cell_line_name
#cellosaurus = cellosaurus.drop(columns=["cell_line_name"])

# 3. rename stripped_cell_line_name -> cell_line_name
#cellosaurus = cellosaurus.rename(columns={"stripped_cell_line_name": "cell_line_name"})

# 4. normalise: strip everything that isn't a-z or 0-9
#cellosaurus["cell_line_name"] = (
#    cellosaurus["cell_line_name"]
#    .str.replace(r"[^a-z0-9]", "", regex=True)
#)

# re-point so tables[...] doesn't silently diverge
#tables["Cellosaurus"] = cellosaurus

In [11]:
# did the rename/drop leave the columns you expect?
print("cell_line_name" in cellosaurus.columns,
      "stripped_cell_line_name" not in cellosaurus.columns)

# did normalisation collapse distinct names into collisions?
before = cellosaurus["cell_line_name"].nunique(dropna=True)
n_rows = cellosaurus["cell_line_name"].notna().sum()
print(f"{n_rows} non-null names, {before} unique after normalisation")

# show any names that now collide (were distinct pre-strip)
dupes = cellosaurus.loc[
    cellosaurus["cell_line_name"].duplicated(keep=False) &
    cellosaurus["cell_line_name"].notna(),
    "cell_line_name"
].value_counts()
print(dupes.head(20))

True True
1839 non-null names, 1839 unique after normalisation
Series([], Name: count, dtype: int64[pyarrow])

In [12]:
def missing_report(df, name=None):
    """Percentage missing per column, sorted worst-first. Shows only cols with >0 missing."""
    n = len(df)
    miss = df.isna().sum()
    pct = (miss / n * 100).round(2)
    out = (
        pd.DataFrame({"n_missing": miss, "pct_missing": pct})
        .query("n_missing > 0")
        .sort_values("pct_missing", ascending=False)
    )
    header = f"{name} — {n:,} rows" if name else f"{n:,} rows"
    print(f"{header}: {len(out)}/{df.shape[1]} cols have missing values")
    return out

# single table
missing_report(cellosaurus, "cellosaurus")

cellosaurus — 1,840 rows: 48/49 cols have missing values

                                    n_missing  pct_missing
refs_parsed.igrhcellid                   1461        79.40
refs_parsed.dsmzcelldive                 1379        74.95
refs_parsed.dsmz                         1379        74.95
refs_parsed.atcc                         1232        66.96
refs_parsed.biogrid_orcs_cell_line       1210        65.76
refs_parsed.bto                          1181        64.18
web pages                                1089        59.18
refs_parsed.efo                          1088        59.13
refs_parsed.chembl-targets                949        51.58
refs_parsed.chembl-cells                  940        51.09
refs_parsed.pubchem_cell_line             937        50.92
refs_parsed.ligea                         907        49.29
refs_parsed.lincs_ldp                     862        46.85
comments                                  830        45.11
refs_parsed.cosmic-clp                    816        44.35
refs_parsed.gdsc                          799        43.42
refs_parsed.pride                         783        42.55
refs_parsed.ega                           705        38.32
refs_parsed.clo                           609        33.10
refs_parsed.progenetix                    598        32.50
refs_parsed.iarc_tp53                     582        31.63
refs_parsed.arrayexpress                  452        24.57
refs_parsed.biosample                     404        21.96
refs_parsed.cosmic                        400        21.74
refs_parsed.pharmacodb                    379        20.60
cosmic_xref                               355        19.29
refs_parsed.geo                           327        17.77
refs_parsed.cancercelllines               163         8.86
synonyms                                  147         7.99
refs_parsed.cell_model_passport           135         7.34
sanger_xref                               135         7.34
str profile data                          131         7.12
diseases                                  125         6.79
age of donor at sampling                   99         5.38
references identifiers                     59         3.21
sex of cell                                56         3.04
rrid                                       22         1.20
refs_parsed.depmap                         15         0.82
depmap_xref                                15         0.82
refs_parsed.wikidata                       14         0.76
cvcl_accession                             14         0.76
date (entry history)                       14         0.76
category                                   14         0.76
species of origin                          14         0.76
cross-references                           14         0.76
cellosaurus_cell_line_name                 14         0.76
_resolution_step                           14         0.76
cell_line_name                              1         0.05

In [ ]:
def drop_high_missing(df, threshold=80.0, name=None, verbose=True):
    """Drop columns whose missing % strictly exceeds `threshold`. Returns a new DataFrame."""
    n = len(df)
    pct = df.isna().sum() / n * 100
    to_drop = pct[pct > threshold].sort_values(ascending=False)

    if verbose:
        tag = f"{name}: " if name else ""
        print(f"{tag}{df.shape[1]} cols -> dropping {len(to_drop)} above {threshold}% missing")
        for col, p in to_drop.items():
            print(f"    {p:6.2f}%  {col}")

    return df.drop(columns=to_drop.index)

cellosaurus = drop_high_missing(cellosaurus, threshold=80.0, name="cellosaurus")
tables["Cellosaurus"] = cellosaurus   # re-point so the dict doesn't diverge

cellosaurus: 49 cols -> dropping 0 above 80.0% missing

In [14]:
cellosaurus

,model_id,cell_line_name,cvcl_accession,synonyms,rrid,_resolution_step,cellosaurus_cell_line_name,cross-references,references identifiers,web pages,...,refs_parsed.efo,refs_parsed.ega,refs_parsed.bto,refs_parsed.chembl-cells,refs_parsed.chembl-targets,refs_parsed.lincs_ldp,refs_parsed.pubchem_cell_line,refs_parsed.cosmic-clp,refs_parsed.gdsc,refs_parsed.biogrid_orcs_cell_line
0,ach-000016,slr21,cvcl_v607,slr 21,cvcl_v607,shipped_reference,slr21,biosample; samn10988415 || cancercelllines; cv...,pubmed=12907621; || pubmed=19470766; || pubmed...,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,ach-000032,mhhcall3,cvcl_0089,mhh-call 3|mhh call 3|mhh-call3|mhh-call3|mhhc...,cvcl_0089,shipped_reference,mhh-call-3,clo; clo_0007716 || arrayexpress; e-mtab-2770 ...,doi=10.1016/b978-0-12-221970-2.50457-5; || pub...,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,ach-000033,ncih1819,cvcl_1497,h1819|h-1819|ncih1819,cvcl_1497,shipped_reference,nci-h1819,clo; clo_0008021 || atcc; crl-5897 || biosampl...,pubmed=8806092; || pubmed=9559342; || pubmed=1...,https://tcpaportal.org/mclp/,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,ach-000043,hs895t,cvcl_0993,hs-895-t|hs 895 t|hs895.t|hs895t|hs895t,cvcl_0993,shipped_reference,hs 895.t,clo; clo_0004200 || efo; efo_0006593 || arraye...,doi=10.1101/166199; || pubmed=20215515; || pub...,<NA>,...,efo_0006593,egas00001000610,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,ach-000049,hekte,cvcl_ws59,hek-te|hekte,cvcl_ws59,shipped_reference,hek te,clo; clo_0037298 || biosample; samn10988406 ||...,pubmed=31068700;,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1835,ach-002393,croap3,cvcl_1810,cro-ap/3|croap3|ap3,cvcl_1810,shipped_reference,cro-ap3,bto; bto:0002725 || clo; clo_0002618 || biosam...,doi=10.1016/b978-0-12-221970-2.50457-5; || pub...,http://www.cells-talk.com/index.php/page/copel...,...,<NA>,<NA>,bto:0002725,<NA>,<NA>,<NA>,<NA>,1297440,1297440,<NA>
1836,ach-002394,geo,cvcl_0271,geo|hct-geo|hct geo,cvcl_0271,shipped_reference,geo,bto; bto:0002892 || mccl; mcc:0000162 || cance...,pubmed=2835152; || pubmed=3349466; || pubmed=6...,<NA>,...,<NA>,<NA>,bto:0002892,<NA>,<NA>,<NA>,<NA>,2164691,2164691,<NA>
1837,ach-002395,huh6clone5,cvcl_1296,huh-6 clone-5|huh-6 clone 5|huh-6 clone 5|huh-...,cvcl_1296,shipped_reference,huh-6 clone 5,arrayexpress; e-mtab-783 || biosample; samn034...,pubmed=57894; || pubmed=6161524; || pubmed=629...,<NA>,...,<NA>,<NA>,<NA>,chembl3308701,<NA>,<NA>,<NA>,907070,907070,<NA>
1838,ach-002396,sarc9371,cvcl_5g89,sarc9371,cvcl_5g89,shipped_reference,sarc9371,cancercelllines; cvcl_5g89 || cell_model_passp...,pubmed=30894373;,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1303910,1303910,<NA>
1839,ach-002397,kmhdash2,cvcl_s641,kmhdash2|kmh2,cvcl_s641,shipped_reference,kmh-2,clo; clo_0037155 || arrayexpress; e-mtab-3610 ...,pubmed=11686581; || pubmed=20215515; || pubmed...,<NA>,...,<NA>,egas00001000978,<NA>,<NA>,<NA>,lcl-1684,<NA>,1298167,1298167,<NA>

In [15]:
from pathlib import Path

PARQUET_CLEAN = Path("/Users/trivenidhamdhere/Documents/MSc Data Science/"
                     "MSc Dissertation - AZ/cleaned_track_data")

out_path = PARQUET_CLEAN / "cellosaurus.parquet"
cellosaurus.to_parquet(out_path, engine="fastparquet", index=False)

# confirm it wrote and reads back with the expected shape/columns
check = pd.read_parquet(out_path, engine="fastparquet")
print(f"saved {out_path.name}: {check.shape}")
print("cell_line_name present:", "cell_line_name" in check.columns)
print("old cols gone:", "stripped_cell_line_name" not in check.columns)

saved cellosaurus.parquet: (1840, 49)
cell_line_name present: True
old cols gone: True